In [92]:
!pip install pandas openpyxl pyproj

import pandas as pd

from pyproj import Transformer

Requirement already satisfied: pandas in /home/codespace/.local/lib/python3.12/site-packages (2.3.1)
Requirement already satisfied: openpyxl in /usr/local/python/3.12.1/lib/python3.12/site-packages (3.1.5)
Requirement already satisfied: pyproj in /usr/local/python/3.12.1/lib/python3.12/site-packages (3.7.2)
Requirement already satisfied: numpy>=1.26.0 in /home/codespace/.local/lib/python3.12/site-packages (from pandas) (2.3.1)
Requirement already satisfied: python-dateutil>=2.8.2 in /home/codespace/.local/lib/python3.12/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /home/codespace/.local/lib/python3.12/site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /home/codespace/.local/lib/python3.12/site-packages (from pandas) (2025.2)
Requirement already satisfied: et-xmlfile in /usr/local/python/3.12.1/lib/python3.12/site-packages (from openpyxl) (2.0.0)
Requirement already satisfied: certifi in /home/codespace/.local/lib/python3.12/site-packages (from pyproj) (2025.7.9)
Requirement already satisfied: six>=1.5 in /home/codespace/.local/lib/python3.12/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

[notice] A new release of pip is available: 25.1.1 -> 25.2
[notice] To update, run: python3 -m pip install --upgrade pip

# Distribuidores

## Listado de Distribuidoras de electricidad según REE

In [93]:
# https://www.esios.ree.es/es/descargas
file_path = 'Excels/124-Distribuidores.xlsx'  

distribuidores_ree_df = pd.read_excel(file_path)

distribuidores_ree_df

,Código,Empresa,Unidad,Fecha Alta,Estado
0,172,"ADURIZ DISTRIBUCIÓN, S.L.",R1-090,2009-01-07,VIGENTE
1,426,"AFRODÍSIO PASCUAL ALONSO, S.L.",R1-284,2009-01-04,VIGENTE
2,112,"AGRI ENERGÍA ELÉCTRICA, S.A.",R1-014,2009-01-03,VIGENTE
3,557,"AGRUPACIÓN DISTRIBUIDORA DE ESCUER, S.L.",R1-310,2009-01-07,VIGENTE
4,420,"ALARCÓN NAVARRO EMPRESA ELÉCTRICA, S.L.",R1-301,2009-01-07,VIGENTE
...,...,...,...,...,...
321,111,"UNIÓN DE DISTRIBUIDORES DE ELECTRICIDAD, S.A. ...",R1-042,2009-01-03,VIGENTE
322,169,"VALL DE SÓLLER ENERGÍA, S.L.U.",R1-056B,2019-01-03,VIGENTE
323,364,"VARGAS Y COMPAÑÍA ELECTRO HARINERA SAN RAMÓN, ...",R1-203,2009-01-07,VIGENTE
324,27,"VIESGO DISTRIBUCIÓN ELÉCTRICA, S.L.",R1-005,2009-01-07,VIGENTE
325,212,"VINALESA DISTRIBUCIÓN DE ENERGÍA, S.L.U.",R1-155,2009-01-07,VIGENTE

## Listado de Distribuidoras de electricidad según CNMC

In [94]:
# https://sede.cnmc.gob.es/listado/censo/1
file_path = 'Excels/distribuidoras.xlsx'  

distribuidores_cnmc_df = pd.read_excel(file_path)

distribuidores_cnmc_df

,NIF empresa,Numero,Nombre empresa,Teléfono gratuito incidencias,Portal de medidas
0,B22215487,R1-285,ENERGIAS DE BENASQUE S.L,900 102 303,https://portal.asemeservicios.com
1,B43986918,R1-360,ELECTRICA MUNICIPAL DE SANTA COLOMA DE QUERALT...,900 102 377,https://portal.asemeservicios.com
2,B63695167,R1-365,ELECTRA REDENERGIA SL,900 373 576,http://gestio.electraredenergia.com
3,B29749199,R1-196,ELECTRICA SERRANIA DE RONDA S.L,900 10 30 56,https://portal.asemeservicios.com
4,A22004675,R1-251,SERVICIOS URBANOS DE CERLER S.A.,900 102 387,https://portal.asemeservicios.com
...,...,...,...,...,...
328,B54863956,R1-063,"DISTRIBUCION ELECTRICA CATRALENSE, SLU",900 101 489,https://portal.asemeservicios.com
329,B98212053,R1-128,ELECTRICA DE CHERA DISTRIBUIDORA SL,900 373 319,http://consumos.grupcev.es
330,B91516351,R1-046,DISTRIBUIDORA ELECTRICA TENTUDIA SL,900 373 891,https://detentudia.oficinavirtual.sercide.com
331,B91516344,R1-199,DISTRIBUIDORA ELECTRICA MONESTERIO SL,900 373 874,https://demonesterio.oficinavirtual.sercide.com
332,B87689733,R1-133,HIDROELECTRICA EL CARMEN REDES SL,900 373 508,https://hidroelcarmen.oficinavirtual.sercide.com

Comparar ambas listas

In [95]:
unidad = distribuidores_ree_df['Unidad'].dropna().str.strip().unique()  
no_orden = distribuidores_cnmc_df['Numero'].dropna().str.strip().unique()  

# Convert to sets for efficient comparison
set_no_orden = set(no_orden)
set_unidad = set(unidad)

common_values = set_no_orden.intersection(set_unidad)  # Same values in both
missing_in_unidad = set_no_orden.difference(set_unidad)  # In Nº de orden but not in Unidad
missing_in_no_orden = set_unidad.difference(set_no_orden)  # In Unidad but not in Nº de orden

print("Número total de valores en el listado de REE:", len(set_unidad))
print("Número total de valores en el listado de la CNMC:", len(set_no_orden))
print("\nNúmero de valores comunes:", len(common_values))

Número total de valores en el listado de REE: 326
Número total de valores en el listado de la CNMC: 333

Número de valores comunes: 323

In [96]:
print("\nValores que están en el listado de la CNMC, pero no en el de REE:")

df_falta_en_REE = distribuidores_cnmc_df[distribuidores_cnmc_df['Numero'].isin(missing_in_unidad)]
df_falta_en_REE.style.hide(axis='index')

Valores que están en el listado de la CNMC, pero no en el de REE:

In [97]:
print("\nValores que están en el listado de REE, pero no en el de la CNMC:")

df_falta_en_CNMC = distribuidores_ree_df[distribuidores_ree_df['Unidad'].isin(missing_in_no_orden)]
df_falta_en_CNMC.style.hide(axis='index')

Valores que están en el listado de REE, pero no en el de la CNMC:

## Distribucion geográfica

In [98]:
def obtener_comunidad_autonoma(provincia):
    # Diccionario con provincias y sus comunidades autónomas
    comunidades = {
        'a coruña': 'Galicia',
        'alava': 'País Vasco',
        'albacete': 'Castilla-La Mancha',
        'alicante': 'Comunidad Valenciana',
        'almería': 'Andalucía',
        'asturias': 'Principado de Asturias',
        'avila': 'Castilla y León',
        'badajoz': 'Extremadura',
        'barcelona': 'Cataluña',
        'bizkaia': 'País Vasco',
        'burgos': 'Castilla y León',
        'caceres': 'Extremadura',
        'cadiz': 'Andalucía',
        'cantabria': 'Cantabria',
        'castellon': 'Comunidad Valenciana',
        'ciudad real': 'Castilla-La Mancha',
        'cordoba': 'Andalucía',
        'cuenca': 'Castilla-La Mancha',
        'girona': 'Cataluña',
        'granada': 'Andalucía',
        'guadalajara': 'Castilla-La Mancha',
        'gipuzkoa': 'País Vasco',
        'huelva': 'Andalucía',
        'huesca': 'Aragón',
        'islas baleares': 'Islas Baleares',
        'jaen': 'Andalucía',
        'la rioja': 'La Rioja',
        'las palmas': 'Islas Canarias',
        'leon': 'Castilla y León',
        'lleida': 'Cataluña',
        'lugo': 'Galicia',
        'madrid': 'Comunidad de Madrid',
        'malaga': 'Andalucía',
        'murcia': 'Región de Murcia',
        'navarra': 'Navarra',
        'ourense': 'Galicia',
        'palencia': 'Castilla y León',
        'pontevedra': 'Galicia',
        'salamanca': 'Castilla y León',
        'santa cruz de tenerife': 'Islas Canarias',
        'segovia': 'Castilla y León',
        'sevilla': 'Andalucía',
        'soria': 'Castilla y León',
        'tarragona': 'Cataluña',
        'teruel': 'Aragón',
        'toledo': 'Castilla-La Mancha',
        'valencia': 'Comunidad Valenciana',
        'valladolid': 'Castilla y León',
        'zamora': 'Castilla y León',
        'zaragoza': 'Aragón'
    }
    
    # Normalizar la entrada (minúsculas y sin tildes básicas)
    if isinstance(provincia, str):  # Asegurarse de que la entrada es una cadena
        provincia = provincia.lower().strip()
        provincia = provincia.replace('á', 'a').replace('é', 'e').replace('í', 'i').replace('ó', 'o').replace('ú', 'u')
        return comunidades.get(provincia, "Provincia no encontrada")
    return "Provincia no encontrada"

# EPRESA

R1-034 (ELECTRICIDAD DE PUERTO REAL, S.A. (EPRESA))

In [161]:
# https://electricaepr.es/solicitud-de-punto-de-suministro/
file_path = 'Excels/EPR_capacidad.xlsx'

# Read the Excel file
EPR_capacidad_df = pd.read_excel(file_path, sheet_name='Hoja1', header=[0]) 

columns = [
    'Provincia',
    'X',
    'Y',
    'Subestacion_REE',
    'Subestacion_EPR'
    ]

# Get unique rows based on 'Identificador de la Subestación'
EPR_df = EPR_capacidad_df[columns].drop_duplicates(subset='Subestacion_EPR')

# Display the resulting DataFrame
EPR_df

  Provincia           X            Y  Subestacion_REE Subestacion_EPR
0     Cádiz  217350.115  4046207.324              NaN       SUB-23001

Convertir Coordenadas mostradas en el sistema de georreferenciación UTM ETRS89, huso 30 a coordenadas en WGS84 (EPSG:4326)

In [162]:
# Definimos el transformador
# EPSG:25830 -> ETRS89 / UTM zona 30N
# EPSG:4326  -> WGS84 (latitud, longitud)
transformer = Transformer.from_crs("EPSG:25830", "EPSG:4326", always_xy=True)

# Crear nuevas columnas con Latitud y Longitud en WGS84
EPR_df["Longitud"], EPR_df["Latitud"] = transformer.transform(EPR_df["X"].values, EPR_df["Y"].values)

Incluimos la comunidad autónoma asociada a cada provincia

In [163]:
# Aplicar la función a la columna 'provincia' y crear una nueva columna 'comunidad_autonoma'
EPR_df['Comunidad'] = EPR_df['Provincia'].apply(obtener_comunidad_autonoma)

EPR_df.to_excel('Excels/EPR.xlsx', index=False)

# CARBAYIN

R1-064 (ELECTRA DE CARBAYIN, S.A.U)

In [164]:
# https://solredis.6eis.es/solredis-web/distributor/27
file_path = 'Excels/CARBAYIN_capacidad.xlsx'

# Read the Excel file
CARBAYIN_capacidad_df = pd.read_excel(file_path, sheet_name='Hoja1', header=[0]) 

columns = [
    'Provincia',
    'X',
    'Y',
    'Subestacion_REE',
    'Subestacion_CARBAYIN'
    ]

# Get unique rows based on 'Identificador de la Subestación'
CARBAYIN_df = CARBAYIN_capacidad_df[columns].drop_duplicates(subset='Subestacion_CARBAYIN')

# Display the resulting DataFrame
CARBAYIN_df

  Provincia       X        Y Subestacion_REE Subestacion_CARBAYIN
0  ASTURIAS  287195  4802770               -        SETLACABAÑONA

Convertir Coordenadas mostradas en el sistema de georreferenciación UTM ETRS89, huso 30 a coordenadas en WGS84 (EPSG:4326)

In [165]:
# Definimos el transformador
# EPSG:25830 -> ETRS89 / UTM zona 30N
# EPSG:4326  -> WGS84 (latitud, longitud)
transformer = Transformer.from_crs("EPSG:25830", "EPSG:4326", always_xy=True)

# Crear nuevas columnas con Latitud y Longitud en WGS84
CARBAYIN_df["Longitud"], CARBAYIN_df["Latitud"] = transformer.transform(CARBAYIN_df["X"].values, CARBAYIN_df["Y"].values)

Incluimos la comunidad autónoma asociada a cada provincia

In [166]:
# Aplicar la función a la columna 'provincia' y crear una nueva columna 'comunidad_autonoma'
CARBAYIN_df['Comunidad'] = CARBAYIN_df['Provincia'].apply(obtener_comunidad_autonoma)

CARBAYIN_df.to_excel('Excels/CARBAYIN.xlsx', index=False)

# PROHIDA

R1-048 (LA PROHIDA DISTRIBUCIÓN ELÉCTRICA, S.L)

In [167]:
# https://solredis.6eis.es/solredis-web/distributor/18
file_path = 'Excels/PROHIDA_capacidad.xlsx'

# Read the Excel file
PROHIDA_capacidad_df = pd.read_excel(file_path, sheet_name='Hoja1', header=[0]) 

columns = [
    'Provincia',
    'X',
    'Y',
    'Subestacion_REE',
    'Subestacion_PROHIDA'
    ]

# Get unique rows based on 'Identificador de la Subestación'
PROHIDA_df = PROHIDA_capacidad_df[columns].drop_duplicates(subset='Subestacion_PROHIDA')

# Display the resulting DataFrame
PROHIDA_df

  Provincia          X           Y Subestacion_REE Subestacion_PROHIDA
0      LEON  229255.29  4759152.58  VILLABLINO 220    SUBSPM2T0500370P
1      LEON  231942.26  4759409.75  VILLABLINO 220    SUBSPM3T1000530P

Convertir Coordenadas mostradas en el sistema de georreferenciación UTM ETRS89, huso 30 a coordenadas en WGS84 (EPSG:4326)

In [168]:
# Definimos el transformador
# EPSG:25830 -> ETRS89 / UTM zona 30N
# EPSG:4326  -> WGS84 (latitud, longitud)
transformer = Transformer.from_crs("EPSG:25830", "EPSG:4326", always_xy=True)

# Crear nuevas columnas con Latitud y Longitud en WGS84
PROHIDA_df["Longitud"], PROHIDA_df["Latitud"] = transformer.transform(PROHIDA_df["X"].values, PROHIDA_df["Y"].values)

Incluimos la comunidad autónoma asociada a cada provincia

In [169]:
# Aplicar la función a la columna 'provincia' y crear una nueva columna 'comunidad_autonoma'
PROHIDA_df['Comunidad'] = PROHIDA_df['Provincia'].apply(obtener_comunidad_autonoma)

PROHIDA_df.to_excel('Excels/PROHIDA.xlsx', index=False)

# LERSA

R1-052 (LERSA ELECTRICITAT, S.L)

In [170]:
# https://solredis.6eis.es/solredis-web/distributor/21
file_path = 'Excels/LERSA_capacidad.xlsx'

# Read the Excel file
LERSA_capacidad_df = pd.read_excel(file_path, sheet_name='Hoja1', header=[0]) 

columns = [
    'Provincia',
    'X',
    'Y',
    'Subestacion_REE',
    'Subestacion_LERSA'
    ]

# Get unique rows based on 'Identificador de la Subestación'
LERSA_df = LERSA_capacidad_df[columns].drop_duplicates(subset='Subestacion_LERSA')

# Display the resulting DataFrame
LERSA_df

  Provincia              X             Y  Subestacion_REE Subestacion_LERSA
0    Girona  434345.715972  4.637367e+07              NaN            SE-132
2    Girona  433284.316240  4.672691e+06              NaN            SE-003
4    Girona  431511.579500  4.674527e+06              NaN            SE-032

Convertir Coordenadas mostradas en el sistema de georreferenciación UTM ETRS89, huso 30 a coordenadas en WGS84 (EPSG:4326)

In [171]:
# Definimos el transformador
# EPSG:25830 -> ETRS89 / UTM zona 30N
# EPSG:4326  -> WGS84 (latitud, longitud)
transformer = Transformer.from_crs("EPSG:25830", "EPSG:4326", always_xy=True)

# Crear nuevas columnas con Latitud y Longitud en WGS84
LERSA_df["Longitud"], LERSA_df["Latitud"] = transformer.transform(LERSA_df["X"].values, LERSA_df["Y"].values)

Incluimos la comunidad autónoma asociada a cada provincia

In [172]:
# Aplicar la función a la columna 'provincia' y crear una nueva columna 'comunidad_autonoma'
LERSA_df['Comunidad'] = LERSA_df['Provincia'].apply(obtener_comunidad_autonoma)

LERSA_df.to_excel('Excels/LERSA.xlsx', index=False)

# CUROS

R1-231 (ELECTRICA CUROS, SL)

In [174]:
# https://www.curosdistribucio.com/ca/capacitats-d-acces-a-la-xarxa/
file_path = 'Excels/CUROS_capacidad.xlsx'

# Read the Excel file
CUROS_capacidad_df = pd.read_excel(file_path, sheet_name='Hoja1', header=[0]) 

columns = [
    'Provincia',
    'X',
    'Y',
    'Subestacion_REE',
    'Subestacion_CUROS'
    ]

# Get unique rows based on 'Identificador de la Subestación'
CUROS_df = CUROS_capacidad_df[columns].drop_duplicates(subset='Subestacion_CUROS')

# Display the resulting DataFrame
CUROS_df

  Provincia         X          Y    Subestacion_REE Subestacion_CUROS
0    Girona  470288.8  4663780.5  SANTA LLOGAIA 400             SEMIE
2    Girona  464549.8  4666028.5        BESCANO 400             SEPAU

Convertir Coordenadas mostradas en el sistema de georreferenciación UTM ETRS89, huso 30 a coordenadas en WGS84 (EPSG:4326)

In [175]:
# Definimos el transformador
# EPSG:25830 -> ETRS89 / UTM zona 30N
# EPSG:4326  -> WGS84 (latitud, longitud)
transformer = Transformer.from_crs("EPSG:25830", "EPSG:4326", always_xy=True)

# Crear nuevas columnas con Latitud y Longitud en WGS84
CUROS_df["Longitud"], CUROS_df["Latitud"] = transformer.transform(CUROS_df["X"].values, CUROS_df["Y"].values)

Incluimos la comunidad autónoma asociada a cada provincia

In [176]:
# Aplicar la función a la columna 'provincia' y crear una nueva columna 'comunidad_autonoma'
CUROS_df['Comunidad'] = CUROS_df['Provincia'].apply(obtener_comunidad_autonoma)

CUROS_df.to_excel('Excels/CUROS.xlsx', index=False)

# PEUSA

R1-020 (PEUSA DISTRIBUCIÓ, S.L.)

In [177]:
# https://www.peusa.org/capacitats-dacces-i-connexio/?lang=es
file_path = 'Excels/PEUSA_capacidad.xlsx'

# Read the Excel file
PEUSA_capacidad_df = pd.read_excel(file_path, sheet_name='Hoja1', header=[0]) 

columns = [
    'Provincia',
    'X',
    'Y',
    'Subestacion_REE',
    'Subestacion_PEUSA'
    ]

# Get unique rows based on 'Identificador de la Subestación'
PEUSA_df = PEUSA_capacidad_df[columns].drop_duplicates(subset='Subestacion_PEUSA')

# Display the resulting DataFrame
PEUSA_df

  Provincia         X           Y Subestacion_REE Subestacion_PEUSA
0    Lleida  862229.6  4695088.63          ADRALL         SE Adrall

Convertir Coordenadas mostradas en el sistema de georreferenciación UTM ETRS89, huso 30 a coordenadas en WGS84 (EPSG:4326)

In [178]:
# Definimos el transformador
# EPSG:25830 -> ETRS89 / UTM zona 30N
# EPSG:4326  -> WGS84 (latitud, longitud)
transformer = Transformer.from_crs("EPSG:25830", "EPSG:4326", always_xy=True)

# Crear nuevas columnas con Latitud y Longitud en WGS84
PEUSA_df["Longitud"], PEUSA_df["Latitud"] = transformer.transform(PEUSA_df["X"].values, PEUSA_df["Y"].values)

Incluimos la comunidad autónoma asociada a cada provincia

In [179]:
# Aplicar la función a la columna 'provincia' y crear una nueva columna 'comunidad_autonoma'
PEUSA_df['Comunidad'] = PEUSA_df['Provincia'].apply(obtener_comunidad_autonoma)

PEUSA_df.to_excel('Excels/PEUSA.xlsx', index=False)

# ELÉCTRICA CONQUENSE DISTRIBUCIÓN S.A.

R1-009 (ELÉCTRICA CONQUENSE DISTRIBUCIÓN S.A.)

In [180]:
# https://www.electricaconquense.es/conexion-a-la-red-electrica/
file_path = 'Excels/CONQUENSE_capacidad.xlsx'

# Read the Excel file
CONQUENSE_capacidad_df = pd.read_excel(file_path, sheet_name='Datos', header=[0]) 

columns = [
    'Provincia',
    'X',
    'Y',
    'Subestacion_REE',
    'Subestacion_CONQUENSE'
    ]

# Get unique rows based on 'Identificador de la Subestación'
CONQUENSE_df = CONQUENSE_capacidad_df[columns].drop_duplicates(subset='Subestacion_CONQUENSE')

# Display the resulting DataFrame
CONQUENSE_df

,Provincia,X,Y,Subestacion_REE,Subestacion_CONQUENSE
0,CUENCA,571408,4434681,BOLARQUE 132 / OLMEDILLA 132,ST EL TERMINILLO

Convertir Coordenadas mostradas en el sistema de georreferenciación UTM ETRS89, huso 30 a coordenadas en WGS84 (EPSG:4326)

In [181]:
# Definimos el transformador
# EPSG:25830 -> ETRS89 / UTM zona 30N
# EPSG:4326  -> WGS84 (latitud, longitud)
transformer = Transformer.from_crs("EPSG:25830", "EPSG:4326", always_xy=True)

# Crear nuevas columnas con Latitud y Longitud en WGS84
CONQUENSE_df["Longitud"], CONQUENSE_df["Latitud"] = transformer.transform(CONQUENSE_df["X"].values, CONQUENSE_df["Y"].values)

Incluimos la comunidad autónoma asociada a cada provincia

In [182]:
# Aplicar la función a la columna 'provincia' y crear una nueva columna 'comunidad_autonoma'
CONQUENSE_df['Comunidad'] = CONQUENSE_df['Provincia'].apply(obtener_comunidad_autonoma)

CONQUENSE_df.to_excel('Excels/CONQUENSE.xlsx', index=False)

# Consolidar todos en un solo fichero

In [183]:
# Diccionario con los dataframes y sus nombres
dfs = {
    "iDE": iDE_df,
    "UFD": UFD_df,
    "EDRD": EDRD_df,
    "EREDES": EREDES_df,
    "VIESGO": VIESGO_df,
    "BEGASA": BEGASA_df,
    "ANELL": ANELL_df,
    "SEDC": SEDC_df,
    "EASA": EASA_df,
    "PITARCH": PITARCH_df,
    "BASSOLS": BASSOLS_df,
    "MAESTRAZGO": MAESTRAZGO_df,
    "GARVEY": GARVEY_df,
    "ADURIZ": ADURIZ_df,
    "AGRI": AGRI_df,
    "CALDENSE": CALDENSE_df,
    "CUERVA": CUERVA_df,
    "GUADIELA": GUADIELA_df,
    "CREVILLENT": CREVILLENT_df,
    "PROHIDA": PROHIDA_df,
    "LERSA": LERSA_df,
    "EPR": EPR_df,
    "SOLLER": SOLLER_df,
    "CUROS": CUROS_df,
    "CARBAYIN": CARBAYIN_df,
    "SERVILIANO": SERVILIANO_df,
    "PEUSA": PEUSA_df,
    "CONQUENSE": CONQUENSE_df
}

# Lista donde guardaremos todos los dataframes transformados
normalized_dfs = []

for name, df in dfs.items():
    # Normalizamos las columnas según el patrón esperado
    df_tmp = pd.DataFrame({
        "Distribuidor": name,
        "Comunidad": df["Comunidad"],
        "Provincia": df["Provincia"],
        "Subestacion": df[f"Subestacion_{name}"],  # Ejemplo: Subestacion_iDE
        "lat": df["Latitud"],
        "lon": df["Longitud"],
        "Subestacion_REE": df["Subestacion_REE"]
    })
    normalized_dfs.append(df_tmp)

# Concatenamos todos en un solo DataFrame
subestaciones_distribucion_df = pd.concat(normalized_dfs, ignore_index=True)

subestaciones_distribucion_df

,Distribuidor,Comunidad,Provincia,Subestacion,lat,lon,Subestacion_REE
0,iDE,Castilla-La Mancha,ALBACETE,ST ALBACETE,39.019468,-1.893831,ROMICA 400
1,iDE,Castilla-La Mancha,ALBACETE,ST ALMANSA,38.852200,-1.087146,BENEJAMA 400
2,iDE,Castilla-La Mancha,ALBACETE,ST BARRAX,39.038773,-2.157478,ROMICA 400
3,iDE,Castilla-La Mancha,ALBACETE,ST CASAS IBAÑEZ,39.274190,-1.471269,ROMICA 400
4,iDE,Castilla-La Mancha,ALBACETE,ST EL BONILLO,38.949934,-2.527131,ROMICA 400
...,...,...,...,...,...,...,...
2770,CUROS,Cataluña,Girona,SEPAU,42.145575,-3.429030,BESCANO 400
2771,CARBAYIN,Principado de Asturias,ASTURIAS,SETLACABAÑONA,43.347649,-5.625634,-
2772,SERVILIANO,Castilla y León,Segovia,SUBEST_GOMEZSERRACIN,41.285240,-4.322074,LASTRAS 400
2773,PEUSA,Cataluña,Lleida,SE Adrall,42.323752,1.395770,ADRALL
2774,CONQUENSE,Castilla-La Mancha,CUENCA,ST EL TERMINILLO,40.059356,-2.162726,BOLARQUE 132 / OLMEDILLA 132

In [184]:
subestaciones_distribucion_df.to_excel('Excels/subestaciones_distribucion.xlsx', index=False)

In [185]:
subestaciones_df = (
    subestaciones_distribucion_df[["Subestacion_REE", "Comunidad"]]
    .drop_duplicates()
    .sort_values(by="Subestacion_REE")
    .reset_index(drop=True)
)

subestaciones_df

    Subestacion_REE               Comunidad
0                 *                Cataluña
1                 *                  Aragón
2                 -  Principado de Asturias
3      A determinar                  Aragón
4      A determinar               Andalucía
..              ...                     ...
552             NaN    Comunidad Valenciana
553             NaN                  Aragón
554             NaN         Castilla y León
555             NaN                Cataluña
556             NaN      Castilla-La Mancha

[557 rows x 2 columns]