In [219]:
!pip install pandas openpyxl pyproj

import pandas as pd

from pyproj import Transformer

Requirement already satisfied: pandas in /home/codespace/.local/lib/python3.12/site-packages (2.3.1)
Requirement already satisfied: openpyxl in /usr/local/python/3.12.1/lib/python3.12/site-packages (3.1.5)
Requirement already satisfied: pyproj in /usr/local/python/3.12.1/lib/python3.12/site-packages (3.7.2)
Requirement already satisfied: numpy>=1.26.0 in /home/codespace/.local/lib/python3.12/site-packages (from pandas) (2.3.1)
Requirement already satisfied: python-dateutil>=2.8.2 in /home/codespace/.local/lib/python3.12/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /home/codespace/.local/lib/python3.12/site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /home/codespace/.local/lib/python3.12/site-packages (from pandas) (2025.2)
Requirement already satisfied: et-xmlfile in /usr/local/python/3.12.1/lib/python3.12/site-packages (from openpyxl) (2.0.0)
Requirement already satisfied: certifi in /home/codespace/.local/lib/python3.12/site-packages (from pyproj) (2025.7.9)
Requirement already satisfied: six>=1.5 in /home/codespace/.local/lib/python3.12/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

[notice] A new release of pip is available: 25.1.1 -> 25.2
[notice] To update, run: python3 -m pip install --upgrade pip

# Distribuidores

## Listado de Distribuidoras de electricidad según REE

In [220]:
# https://www.esios.ree.es/es/descargas
file_path = 'Excels/124-Distribuidores.xlsx'  

distribuidores_ree_df = pd.read_excel(file_path)

distribuidores_ree_df

,Código,Empresa,Unidad,Fecha Alta,Estado
0,172,"ADURIZ DISTRIBUCIÓN, S.L.",R1-090,2009-01-07,VIGENTE
1,426,"AFRODÍSIO PASCUAL ALONSO, S.L.",R1-284,2009-01-04,VIGENTE
2,112,"AGRI ENERGÍA ELÉCTRICA, S.A.",R1-014,2009-01-03,VIGENTE
3,557,"AGRUPACIÓN DISTRIBUIDORA DE ESCUER, S.L.",R1-310,2009-01-07,VIGENTE
4,420,"ALARCÓN NAVARRO EMPRESA ELÉCTRICA, S.L.",R1-301,2009-01-07,VIGENTE
...,...,...,...,...,...
321,111,"UNIÓN DE DISTRIBUIDORES DE ELECTRICIDAD, S.A. ...",R1-042,2009-01-03,VIGENTE
322,169,"VALL DE SÓLLER ENERGÍA, S.L.U.",R1-056B,2019-01-03,VIGENTE
323,364,"VARGAS Y COMPAÑÍA ELECTRO HARINERA SAN RAMÓN, ...",R1-203,2009-01-07,VIGENTE
324,27,"VIESGO DISTRIBUCIÓN ELÉCTRICA, S.L.",R1-005,2009-01-07,VIGENTE
325,212,"VINALESA DISTRIBUCIÓN DE ENERGÍA, S.L.U.",R1-155,2009-01-07,VIGENTE

## Listado de Distribuidoras de electricidad según CNMC

In [221]:
# https://sede.cnmc.gob.es/listado/censo/1
file_path = 'Excels/distribuidoras.xlsx'  

distribuidores_cnmc_df = pd.read_excel(file_path)

distribuidores_cnmc_df

,NIF empresa,Numero,Nombre empresa,Teléfono gratuito incidencias,Portal de medidas
0,B22215487,R1-285,ENERGIAS DE BENASQUE S.L,900 102 303,https://portal.asemeservicios.com
1,B43986918,R1-360,ELECTRICA MUNICIPAL DE SANTA COLOMA DE QUERALT...,900 102 377,https://portal.asemeservicios.com
2,B63695167,R1-365,ELECTRA REDENERGIA SL,900 373 576,http://gestio.electraredenergia.com
3,B29749199,R1-196,ELECTRICA SERRANIA DE RONDA S.L,900 10 30 56,https://portal.asemeservicios.com
4,A22004675,R1-251,SERVICIOS URBANOS DE CERLER S.A.,900 102 387,https://portal.asemeservicios.com
...,...,...,...,...,...
328,B54863956,R1-063,"DISTRIBUCION ELECTRICA CATRALENSE, SLU",900 101 489,https://portal.asemeservicios.com
329,B98212053,R1-128,ELECTRICA DE CHERA DISTRIBUIDORA SL,900 373 319,http://consumos.grupcev.es
330,B91516351,R1-046,DISTRIBUIDORA ELECTRICA TENTUDIA SL,900 373 891,https://detentudia.oficinavirtual.sercide.com
331,B91516344,R1-199,DISTRIBUIDORA ELECTRICA MONESTERIO SL,900 373 874,https://demonesterio.oficinavirtual.sercide.com
332,B87689733,R1-133,HIDROELECTRICA EL CARMEN REDES SL,900 373 508,https://hidroelcarmen.oficinavirtual.sercide.com

Comparar ambas listas

In [222]:
unidad = distribuidores_ree_df['Unidad'].dropna().str.strip().unique()  
no_orden = distribuidores_cnmc_df['Numero'].dropna().str.strip().unique()  

# Convert to sets for efficient comparison
set_no_orden = set(no_orden)
set_unidad = set(unidad)

common_values = set_no_orden.intersection(set_unidad)  # Same values in both
missing_in_unidad = set_no_orden.difference(set_unidad)  # In Nº de orden but not in Unidad
missing_in_no_orden = set_unidad.difference(set_no_orden)  # In Unidad but not in Nº de orden

print("Número total de valores en el listado de REE:", len(set_unidad))
print("Número total de valores en el listado de la CNMC:", len(set_no_orden))
print("\nNúmero de valores comunes:", len(common_values))

Número total de valores en el listado de REE: 326
Número total de valores en el listado de la CNMC: 333

Número de valores comunes: 323

In [223]:
print("\nValores que están en el listado de la CNMC, pero no en el de REE:")

df_falta_en_REE = distribuidores_cnmc_df[distribuidores_cnmc_df['Numero'].isin(missing_in_unidad)]
df_falta_en_REE.style.hide(axis='index')

Valores que están en el listado de la CNMC, pero no en el de REE:

In [224]:
print("\nValores que están en el listado de REE, pero no en el de la CNMC:")

df_falta_en_CNMC = distribuidores_ree_df[distribuidores_ree_df['Unidad'].isin(missing_in_no_orden)]
df_falta_en_CNMC.style.hide(axis='index')

Valores que están en el listado de REE, pero no en el de la CNMC:

## Distribucion geográfica

In [225]:
def obtener_comunidad_autonoma(provincia):
    # Diccionario con provincias y sus comunidades autónomas
    comunidades = {
        'a coruña': 'Galicia',
        'alava': 'País Vasco',
        'albacete': 'Castilla-La Mancha',
        'alicante': 'Comunidad Valenciana',
        'almería': 'Andalucía',
        'asturias': 'Principado de Asturias',
        'avila': 'Castilla y León',
        'badajoz': 'Extremadura',
        'barcelona': 'Cataluña',
        'bizkaia': 'País Vasco',
        'burgos': 'Castilla y León',
        'caceres': 'Extremadura',
        'cadiz': 'Andalucía',
        'cantabria': 'Cantabria',
        'castellon': 'Comunidad Valenciana',
        'ciudad real': 'Castilla-La Mancha',
        'cordoba': 'Andalucía',
        'cuenca': 'Castilla-La Mancha',
        'girona': 'Cataluña',
        'granada': 'Andalucía',
        'guadalajara': 'Castilla-La Mancha',
        'gipuzkoa': 'País Vasco',
        'huelva': 'Andalucía',
        'huesca': 'Aragón',
        'islas baleares': 'Islas Baleares',
        'jaen': 'Andalucía',
        'la rioja': 'La Rioja',
        'las palmas': 'Islas Canarias',
        'leon': 'Castilla y León',
        'lleida': 'Cataluña',
        'lugo': 'Galicia',
        'madrid': 'Comunidad de Madrid',
        'malaga': 'Andalucía',
        'murcia': 'Región de Murcia',
        'navarra': 'Navarra',
        'ourense': 'Galicia',
        'palencia': 'Castilla y León',
        'pontevedra': 'Galicia',
        'salamanca': 'Castilla y León',
        'santa cruz de tenerife': 'Islas Canarias',
        'segovia': 'Castilla y León',
        'sevilla': 'Andalucía',
        'soria': 'Castilla y León',
        'tarragona': 'Cataluña',
        'teruel': 'Aragón',
        'toledo': 'Castilla-La Mancha',
        'valencia': 'Comunidad Valenciana',
        'valladolid': 'Castilla y León',
        'zamora': 'Castilla y León',
        'zaragoza': 'Aragón'
    }
    
    # Normalizar la entrada (minúsculas y sin tildes básicas)
    if isinstance(provincia, str):  # Asegurarse de que la entrada es una cadena
        provincia = provincia.lower().strip()
        provincia = provincia.replace('á', 'a').replace('é', 'e').replace('í', 'i').replace('ó', 'o').replace('ú', 'u')
        return comunidades.get(provincia, "Provincia no encontrada")
    return "Provincia no encontrada"

# I-DE Redes Eléctricas Inteligentes, S.A.U. (Grupo Iberdrola)

R1-001

In [226]:
# https://www.i-de.es/conexion-red-electrica/produccion-energia/mapa-capacidad-acceso
file_path = 'Excels/iDE_capacidad.xlsx'

# Read the Excel file
iDE_capacidad_df = pd.read_excel(file_path, sheet_name='Table 1', header=[0]) 

columns = [
    'Subestacion_iDE',
    'Municipio',
    'Provincia',
    'X',
    'Y',
    'Subestacion_REE'
]

# Get unique rows based on 'Identificador de la Subestación'
iDE_df = iDE_capacidad_df[columns].drop_duplicates(subset='Subestacion_iDE')

# Display the resulting DataFrame
iDE_df

,Subestacion_iDE,Municipio,Provincia,X,Y,Subestacion_REE
0,ST ALBACETE,ALBACETE,ALBACETE,595760.12,4319519.01,ROMICA 400
5,ST ALMANSA,ALMANSA,ALBACETE,665988.08,4302113.75,BENEJAMA 400
10,ST BARRAX,BARRAX,ALBACETE,572916.18,4321416.97,ROMICA 400
13,ST CASAS IBAÑEZ,CASAS IBAÑEZ,ALBACETE,631866.24,4348318.27,ROMICA 400
17,ST EL BONILLO,EL BONILLO,ALBACETE,540975.48,4311327.00,ROMICA 400
...,...,...,...,...,...,...
2983,STR TORO,TORO,ZAMORA,300258.21,4600161.15,ZAMORA 220
2987,STR VALDERREY,ZAMORA,ZAMORA,269756.98,4600268.56,ZAMORA 220
2991,STR VENTOSA,BENAVENTE,ZAMORA,277904.21,4652035.08,VILECHA 400
2993,STR VILLABRAZARO,VILLABRAZARO,ZAMORA,277490.35,4659689.16,VILECHA 400
2995,STR VILLALPANDO,VILLALPANDO,ZAMORA,297159.91,4638778.49,VILECHA 400

X and Y are the geographical coordinates of the subestation in the ETRS89 coordinate system expressed in meters. I want to convert them into WGS84 (EPSG:4326) coordinate system

In [227]:
# Definimos el transformador
# EPSG:25830 -> ETRS89 / UTM zona 30N
# EPSG:4326  -> WGS84 (latitud, longitud)
transformer = Transformer.from_crs("EPSG:25830", "EPSG:4326", always_xy=True)

# Crear nuevas columnas con Latitud y Longitud en WGS84
iDE_df["Longitud"], iDE_df["Latitud"] = transformer.transform(iDE_df["X"].values, iDE_df["Y"].values)

Incluimos la comunidad autónoma asociada a cada provincia

In [228]:
# Aplicar la función a la columna 'provincia' y crear una nueva columna 'comunidad_autonoma'
iDE_df['Comunidad'] = iDE_df['Provincia'].apply(obtener_comunidad_autonoma)

iDE_df.to_excel('Excels/iDE.xlsx', index=False)

# UFD DISTRIBUCIÓN ELECTRICIDAD, S.A. (Grupo Naturgy)

R1-002

In [229]:
# https://www.ufd.es/capacidad-de-acceso-de-generacion/
file_path = 'Excels/UFD_capacidad.xlsx'

# Read the Excel file
UFD_capacidad_df = pd.read_excel(file_path, sheet_name='Escenario Propuesta', header=[0]) 

columns = [
    'Subestacion_UFD',
    'Provincia',
    'X',
    'Y',
    'Subestacion_REE'
    ]

# Get unique rows based on 'Identificador de la Subestación'
UFD_df = UFD_capacidad_df[columns].drop_duplicates(subset='Subestacion_UFD')

UFD_df

      Subestacion_UFD    Provincia          X           Y   Subestacion_REE
0         C.T. NARCEA     ASTURIAS  224554.00  4798844.00        NARCEA 400
3       C.H.BURGUILLO        AVILA  370636.00  4476221.00  VILLAVICIOSA 400
6     C.H.PUENTENUEVO        AVILA  377683.00  4474588.00  VILLAVICIOSA 400
9                 ZAL    BARCELONA  929574.00  4586213.00           ZAL 220
12           ABENOJAR  CIUDAD REAL  382415.00  4305410.00       ALARCOS 220
...               ...          ...        ...         ...               ...
2007         YELES II       TOLEDO  432702.00  4441860.00     VALDEMORO 220
2013      LOS YEBENES       TOLEDO  426533.00  4380882.00    MADRIDEJOS 220
2019            YEPES       TOLEDO  447070.00  4416268.00     VALDEMORO 220
2025         COBREROS       ZAMORA  197049.54  4662902.57   SAN AGUSTIN 220
2028    MILLA DE TERA       ZAMORA  237921.00  4655964.00   COMPOSTILLA 400

[347 rows x 5 columns]

Coordenadas mostradas en el sistema de georreferenciación UTM ETRS89, huso 29 para las provincias de Lugo, Orense, La Coruña y Pontevedra. El resto de las provincias se muestran con el sistema de georreferenciación UTM ETRS89, huso 30. Convertir a coordenadas en WGS84 (EPSG:4326)

In [230]:
# Lista de provincias en huso 29
provincias_huso29 = ["LUGO", "OURENSE", "A CORUÑA", "PONTEVEDRA"]

# Transformadores
transformer29 = Transformer.from_crs("EPSG:25829", "EPSG:4326", always_xy=True)
transformer30 = Transformer.from_crs("EPSG:25830", "EPSG:4326", always_xy=True)

# Función para convertir según provincia
def convertir_coord(row):
    x, y = row["X"], row["Y"]
    if row["Provincia"] in provincias_huso29:
        lon, lat = transformer29.transform(x, y)
    else:
        lon, lat = transformer30.transform(x, y)
    return pd.Series([lon, lat])

# Aplicar la conversión
UFD_df[["Longitud", "Latitud"]] = UFD_df.apply(convertir_coord, axis=1)

Incluimos la comunidad autónoma asociada a cada provincia

In [231]:
# Aplicar la función a la columna 'provincia' y crear una nueva columna 'comunidad_autonoma'
UFD_df['Comunidad'] = UFD_df['Provincia'].apply(obtener_comunidad_autonoma)

UFD_df.to_excel('Excels/UFD.xlsx', index=False)

# EDISTRIBUCIÓN REDES DIGITALES, S.L. (Grupo Enel)

R1-299, R1-299B

In [232]:
# https://www.edistribucion.com/es/red-electrica/Nodos_capacidad_acceso.html
file_path = 'Excels/EDRD_capacidad.xlsx'

# Read the Excel file
EDRD_capacidad_df = pd.read_excel(file_path, sheet_name='Table 1', header=[0]) 

columns = [
    'Comunidad',
    'Provincia',
    'Municipio',
    'Subestacion_EDRD',
    'Latitud',
    'Longitud',
    'Subestacion_REE'
    ]

# Get unique rows based on 'Identificador de la Subestación'
EDRD_df = EDRD_capacidad_df[columns].drop_duplicates(subset='Subestacion_EDRD')

EDRD_df

,Comunidad,Provincia,Municipio,Subestacion_EDRD,Latitud,Longitud,Subestacion_REE
0,01 - Andalucía,Almería,Roquetas de Mar,AGUADULC,36.813531,-2.598941,BERJA 220
2,01 - Andalucía,Almería,Albox,ALBOX,37.367600,-2.142758,LITORAL 400
4,01 - Andalucía,Almería,Alcolea,ALCOLEA,36.969459,-2.963403,BERJA 220
6,01 - Andalucía,Almería,Almería,ANDARAX,36.839727,-2.431844,LITORAL 400
9,01 - Andalucía,Almería,Almería,BELEN,36.850365,-2.474578,LITORAL 400
...,...,...,...,...,...,...,...
1829,11 - Extremadura,Badajoz,Castuera,ZUJAR,38.916248,-5.478426,VALDECABALLEROS 400
1830,12 - Galicia,"Coruña, A","Pontes de García Rodríguez, As",TESOURO,43.452366,-7.892504,PUENTES G.R. 400
1832,12 - Galicia,Ourense,Viana do Bolo,S.AGUSTIN,42.153497,-7.062870,S.AGUSTIN 220
1834,12 - Galicia,Ourense,Viana do Bolo,S.SEBAS,42.126101,-6.985063,S.AGUSTIN 220
1836,15 - Navarra,Navarra,Roncal/Erronkari,RONCAL,42.794116,-0.959489,SABIÑANIGO 220

In [233]:
# Eliminar el prefijo numérico y el guion
EDRD_df["Comunidad"] = EDRD_df["Comunidad"].str.replace(r'^\d+\s*-\s*', '', regex=True)

EDRD_df.to_excel('Excels/EDRD.xlsx', index=False)

# E-REDES Distribución Eléctrica (Grupo E-REDES)

R1-363 (ELECTRA DEL LLOBREGAT ENERGIA, S.L.), R1-008 (HIDROCANTÁBRICO DISTRIBUCIÓN ELÉCTRICA, S.A.)

In [234]:
# https://www.eredesdistribucion.es/mapa-interactivo-de-la-red
file_path = 'Excels/EREDES_capacidad.xlsx'

# Read the Excel file
EREDES_capacidad_df = pd.read_excel(file_path, sheet_name='Table 1', header=[0]) 

columns = [
    'Provincia',
    'X',
    'Y',
    'Subestacion_REE',
    'Subestacion_EREDES'
    ]

# Get unique rows based on 'Identificador de la Subestación'
EREDES_df = EREDES_capacidad_df[columns].drop_duplicates(subset='Subestacion_EREDES')

# Display the resulting DataFrame
EREDES_df

,Provincia,X,Y,Subestacion_REE,Subestacion_EREDES
0,Asturias,237341.32,4810817.19,SALAS 400,SE/CR ZORRINA
11,Asturias,312856.24,4803568.88,CARRIO 220,SE/CR VILLAMAYOR
20,Asturias,297336.57,4820931.19,CARRIO 220,SE/CR VENTA LAS RANAS
27,Asturias,274840.01,4801169.23,LADA 400,SE/CR VEGUIN 2
31,Asturias,274246.83,4832516.14,TABIELLA 220,SE/CR URB LA VALLINA 1
...,...,...,...,...,...
1214,Asturias,322490.10,4807772.73,LADA 400,SE ARRIONDAS
1227,Asturias,264322.28,4826404.03,TABIELLA 220,SE AMBULATORIO
1233,Asturias,273525.66,4814022.64,SIERO 220,SE ALIMERKA
1238,Valencia,715067.75,4369943.31,QUART DE POBLET 220,SE ALDAIA
1249,Barcelona,907279.22,4637263.42,*,SE PLANS DE LA SALA

Convertir Coordenadas mostradas en el sistema de georreferenciación UTM ETRS89, huso 30 a coordenadas en WGS84 (EPSG:4326)

In [235]:
# Definimos el transformador
# EPSG:25830 -> ETRS89 / UTM zona 30N
# EPSG:4326  -> WGS84 (latitud, longitud)
transformer = Transformer.from_crs("EPSG:25830", "EPSG:4326", always_xy=True)

# Crear nuevas columnas con Latitud y Longitud en WGS84
EREDES_df["Longitud"], EREDES_df["Latitud"] = transformer.transform(EREDES_df["X"].values, EREDES_df["Y"].values)

Incluimos la comunidad autónoma asociada a cada provincia

In [236]:
# Aplicar la función a la columna 'provincia' y crear una nueva columna 'comunidad_autonoma'
EREDES_df['Comunidad'] = EREDES_df['Provincia'].apply(obtener_comunidad_autonoma)

EREDES_df.to_excel('Excels/EREDES.xlsx', index=False)

# VIESGO distribución (Grupo EON)

R1-005 (VIESGO DISTRIBUCIÓN ELÉCTRICA, S.L.)

In [237]:
# https://www.viesgodistribucion.com/mapa-interactivo-de-la-red
file_path = 'Excels/VIESGO_capacidad.xlsx'

# Read the Excel file
VIESGO_capacidad_df = pd.read_excel(file_path, sheet_name='Table 1', header=[0]) 

columns = [
    'Provincia',
    'X',
    'Y',
    'Subestacion_REE',
    'Subestacion_VIESGO'
    ]

# Get unique rows based on 'Identificador de la Subestación'
VIESGO_df = VIESGO_capacidad_df[columns].drop_duplicates(subset='Subestacion_VIESGO')

# Display the resulting DataFrame
VIESGO_df

     Provincia       X        Y Subestacion_REE Subestacion_VIESGO
0     ASTURIAS  201593  4797451     EL PALO 400            EL PALO
3     ASTURIAS  187038  4794995       PESOZ 400              SANZO
15    ASTURIAS  215357  4825840       SALAS 400             ALMUÑA
31    ASTURIAS  198270  4820752       SALAS 400              ARBON
46    ASTURIAS  190402  4811140       SALAS 400             DOIRAS
...        ...     ...      ...             ...                ...
1127      LUGO  146551  4818040      LUDRIO 400          MONDOÑEDO
1134      LUGO  131875  4772615      LUDRIO 400         SAN CIBRAO
1137      LUGO  122821  4818556      P.G.R. 400              CARBA
1142      LUGO  121787  4806251      P.G.R. 400        SETE PONTES
1146      LUGO  170870  4828332       SALAS 400            RIBADEO

[96 rows x 5 columns]

Convertir Coordenadas mostradas en el sistema de georreferenciación UTM ETRS89, huso 30 a coordenadas en WGS84 (EPSG:4326)

In [238]:
# Definimos el transformador
# EPSG:25830 -> ETRS89 / UTM zona 30N
# EPSG:4326  -> WGS84 (latitud, longitud)
transformer = Transformer.from_crs("EPSG:25830", "EPSG:4326", always_xy=True)

# Crear nuevas columnas con Latitud y Longitud en WGS84
VIESGO_df["Longitud"], VIESGO_df["Latitud"] = transformer.transform(VIESGO_df["X"].values, VIESGO_df["Y"].values)

Incluimos la comunidad autónoma asociada a cada provincia

In [239]:
# Aplicar la función a la columna 'provincia' y crear una nueva columna 'comunidad_autonoma'
VIESGO_df['Comunidad'] = VIESGO_df['Provincia'].apply(obtener_comunidad_autonoma)

VIESGO_df.to_excel('Excels/VIESGO.xlsx', index=False)

# ANELL

R1-018 (ESTABANELL Y PAHISA ENERGÍA, S.A.)

In [240]:
# https://www.e-anell.cat/es/mapa-de-capacidades/
file_path = 'Excels/ANELL_capacidad.xlsx'

# Read the Excel file
ANELL_capacidad_df = pd.read_excel(file_path, sheet_name='Table 1', header=[0]) 

columns = [
    'Provincia',
    'X',
    'Y',
    'Subestacion_REE',
    'Subestacion_ANELL'
    ]

# Get unique rows based on 'Identificador de la Subestación'
ANELL_df = ANELL_capacidad_df[columns].drop_duplicates(subset='Subestacion_ANELL')

# Display the resulting DataFrame
ANELL_df

,Provincia,X,Y,Subestacion_REE,Subestacion_ANELL
0,Barcelona,439369.68,4613488.87,FRANQUESES 220,AMETLLA 20kV
1,Barcelona,439369.68,4613488.87,FRANQUESES 220,AMETLLA 40kV
2,Barcelona,434611.73,4628697.73,CENTELLES 220,CENTELLES 40kV
3,Barcelona,437256.49,4611339.56,FRANQUESES 220,GAFA 40kV
4,Barcelona,440241.97,4610346.21,FRANQUESES 220,MARGENS 20kV
5,Barcelona,440241.97,4610346.21,FRANQUESES 220,MARGENS 40kV
6,Barcelona,435716.08,4628009.30,CENTELLES 220,MOTOR 40kV
7,Barcelona,440441.62,4606714.54,FRANQUESES 220,REC 20kV
8,Barcelona,440441.62,4606714.54,FRANQUESES 220,REC 5kV
9,Barcelona,442179.18,4658327.72,VIC 220,SANT PERE 20kV
10,Barcelona,442179.18,4658327.72,VIC 220,SANT PERE 40kV
11,Barcelona,442179.18,4658327.72,VIC 220,SANT PERE 5kV
12,Barcelona,440512.56,4645125.56,VIC 220,VIC 40kV
13,NaN,NaN,NaN,NaN,Información complementaria sobre sobre los nudos:
14,NaN,NaN,NaN,NaN,(1) Nudo a desaparecer\n(2) Previsto cambio de...

Convertir Coordenadas mostradas en el sistema de georreferenciación UTM X ERTS89-31N a coordenadas en WGS84 (EPSG:4326)

In [241]:
# Definimos el transformador
# EPSG:25831 -> ETRS89 / UTM zona 31N
# EPSG:4326  -> WGS84 (latitud, longitud)
transformer = Transformer.from_crs("EPSG:25831", "EPSG:4326", always_xy=True)

# Crear nuevas columnas con Latitud y Longitud en WGS84
ANELL_df["Longitud"], ANELL_df["Latitud"] = transformer.transform(ANELL_df["X"].values, ANELL_df["Y"].values)

Incluimos la comunidad autónoma asociada a cada provincia

In [242]:
# Aplicar la función a la columna 'provincia' y crear una nueva columna 'comunidad_autonoma'
ANELL_df['Comunidad'] = ANELL_df['Provincia'].apply(obtener_comunidad_autonoma)

ANELL_df.to_excel('Excels/ANELL.xlsx', index=False)

# SEDC

R1-021 (SUMINISTRADORA ELECTRICA DE CADIZ, S.A)

In [243]:
# https://solredis.asemeservicios.com/solredis-web/distributor/7
file_path = 'Excels/SEDC_capacidad.xlsx'

# Read the Excel file
SEDC_capacidad_df = pd.read_excel(file_path, sheet_name='R1021', header=[0]) 

columns = [
    'Provincia',
    'X',
    'Y',
    'Subestacion_REE',
    'Subestacion_SEDC'
    ]

# Get unique rows based on 'Identificador de la Subestación'
SEDC_df = SEDC_capacidad_df[columns].drop_duplicates(subset='Subestacion_SEDC')

# Display the resulting DataFrame
SEDC_df

   Provincia           X            Y  Subestacion_REE  Subestacion_SEDC
0      Cádiz  205072.975  4048493.494              NaN           1463897
2      Cádiz  207570.921  4044884.739              NaN           1463839
6      Cádiz  205740.426  4046793.601              NaN           1463769
8      Cádiz  207380.211  4043304.900              NaN           1463783
10     Cádiz  207397.716  4043336.071              NaN           1463825
12     Cádiz  206349.464  4046935.562              NaN           2291763
15     Cádiz  207038.810  4044232.327              NaN           1463811
17     Cádiz  206415.658  4046418.051              NaN           1554117
19     Cádiz  207598.161  4045078.231              NaN           1463910
21     Cádiz  204204.528  4048130.571              NaN           1108231
23     Cádiz  206459.438  4045561.189              NaN           1463923
25     Cádiz  206740.445  4045796.763              NaN           1463937
27     Cádiz  205584.618  4047842.304              NaN           1472567

Convertir Coordenadas mostradas en el sistema de georreferenciación UTM ETRS89, huso 30 a coordenadas en WGS84 (EPSG:4326)

In [244]:
# Definimos el transformador
# EPSG:25830 -> ETRS89 / UTM zona 30N
# EPSG:4326  -> WGS84 (latitud, longitud)
transformer = Transformer.from_crs("EPSG:25830", "EPSG:4326", always_xy=True)

# Crear nuevas columnas con Latitud y Longitud en WGS84
SEDC_df["Longitud"], SEDC_df["Latitud"] = transformer.transform(SEDC_df["X"].values, SEDC_df["Y"].values)

Incluimos la comunidad autónoma asociada a cada provincia

In [245]:
# Aplicar la función a la columna 'provincia' y crear una nueva columna 'comunidad_autonoma'
SEDC_df['Comunidad'] = SEDC_df['Provincia'].apply(obtener_comunidad_autonoma)

SEDC_df.to_excel('Excels/SEDC.xlsx', index=False)

# Begasa

R1-003 (BARRAS ELÉCTRICAS GALAICO-ASTURIANAS S.A.)

In [246]:
# https://www.begasa.es/mapa-interactivo-de-la-red
file_path = 'Excels/BEGASA_capacidad.xlsx'

# Read the Excel file
BEGASA_capacidad_df = pd.read_excel(file_path, sheet_name='R1-003', header=[0]) 

columns = [
    'Provincia',
    'X',
    'Y',
    'Subestacion_REE',
    'Subestacion_BEGASA'
    ]

# Get unique rows based on 'Identificador de la Subestación'
BEGASA_df = BEGASA_capacidad_df[columns].drop_duplicates(subset='Subestacion_BEGASA')

# Display the resulting DataFrame
BEGASA_df

   Provincia          X           Y  Subestacion_REE Subestacion_BEGASA
0       Lugo  155519.80  4821904.95  Boimente 400 kV          BARREIROS
2       Lugo  121983.30  4784946.43    P.G.R. 400 kV            BEGONTE
4       Lugo  146778.05  4844034.29  Boimente 400 kV             BURELA
6       Lugo  128628.82  4772583.32    Ludrio 400 kV            C_CONDE
7       Lugo  127938.28  4772949.79    Ludrio 400 kV         CASTIÑEIRO
8       Lugo  128539.02  4776217.69    Ludrio 400 kV               CEAO
10      Lugo  163587.04  4778438.62    Ludrio 400 kV         FONSAGRADA
11      Lugo  155353.46  4830679.67  Boimente 400 kV                FOZ
13      Lugo  140726.06  4784560.66    Ludrio 400 kV             LUDRIO
14      Lugo  128843.89  4842876.89  Boimente 400 kV            MAGAZOS
16      Lugo  149251.87  4794477.79    Ludrio 400 kV              MEIRA
18      Lugo  129424.07  4770617.51    Ludrio 400 kV           MERCEDES
19      Lugo  146550.67  4818040.12    Ludrio 400 kV          MONDOÑEDO
20      Lugo  170870.16  4828331.61     Salas 400 kV            RIBADEO
21      Lugo  131875.30  4772615.07    Ludrio 400 kV         SAN_CIBRAO
22      Lugo  121786.50  4806250.84    P.G.R. 400 kV        SETE PONTES

Convertir Coordenadas mostradas en el sistema de georreferenciación UTM ETRS89, huso 30 a coordenadas en WGS84 (EPSG:4326)

In [247]:
# Definimos el transformador
# EPSG:25830 -> ETRS89 / UTM zona 30N
# EPSG:4326  -> WGS84 (latitud, longitud)
transformer = Transformer.from_crs("EPSG:25830", "EPSG:4326", always_xy=True)

# Crear nuevas columnas con Latitud y Longitud en WGS84
BEGASA_df["Longitud"], BEGASA_df["Latitud"] = transformer.transform(BEGASA_df["X"].values, BEGASA_df["Y"].values)

Incluimos la comunidad autónoma asociada a cada provincia

In [248]:
# Aplicar la función a la columna 'provincia' y crear una nueva columna 'comunidad_autonoma'
BEGASA_df['Comunidad'] = BEGASA_df['Provincia'].apply(obtener_comunidad_autonoma)

BEGASA_df.to_excel('Excels/BEGASA.xlsx', index=False)

# EASA

R1-026 (ENERGÍAS DE ARAGÓN I S.L.)

In [249]:
# https://www.edistribucion.com/es/red-electrica/nodos-capacidad-red/capacidad-generacion.html
file_path = 'Excels/EASA_capacidad.xlsx'

# Read the Excel file
EASA_capacidad_df = pd.read_excel(file_path, sheet_name='R1026', header=[0]) 

columns = [
    'Provincia',
    'X',
    'Y',
    'Subestacion_REE',
    'Subestacion_EASA'
    ]

# Get unique rows based on 'Identificador de la Subestación'
EASA_df = EASA_capacidad_df[columns].drop_duplicates(subset='Subestacion_EASA')

# Display the resulting DataFrame
EASA_df

  Provincia              X             Y Subestacion_REE Subestacion_EASA
0    Huesca  726456.392820  4.738115e+06  SABIÑANIGO 220            BAÑOS
1    Huesca  786538.171083  4.721081e+06      ERISTE 220           ERISTE
2    Huesca  720582.449142  4.734211e+06  SABIÑANIGO 220            PUEYO
3    Huesca  717030.336234  4.710543e+06  SABIÑANIGO 220       SABIÑANIGO
4    Huesca  718136.190594  4.738789e+06  SABIÑANIGO 220          SALLENT

Convertir Coordenadas mostradas en el sistema de georreferenciación UTM ETRS89, huso 30 a coordenadas en WGS84 (EPSG:4326)

In [250]:
# Definimos el transformador
# EPSG:25830 -> ETRS89 / UTM zona 30N
# EPSG:4326  -> WGS84 (latitud, longitud)
transformer = Transformer.from_crs("EPSG:25830", "EPSG:4326", always_xy=True)

# Crear nuevas columnas con Latitud y Longitud en WGS84
EASA_df["Longitud"], EASA_df["Latitud"] = transformer.transform(EASA_df["X"].values, EASA_df["Y"].values)

Incluimos la comunidad autónoma asociada a cada provincia

In [251]:
# Aplicar la función a la columna 'provincia' y crear una nueva columna 'comunidad_autonoma'
EASA_df['Comunidad'] = EASA_df['Provincia'].apply(obtener_comunidad_autonoma)

EASA_df.to_excel('Excels/EASA.xlsx', index=False)

# PITARCH

R1-049 (ELECTRICAS PITARCH DISTRIBUCION SLU), R1-035 (Eléctrica del Oeste Distribución S.L.U.), R1-164(DISTRIBUCIÓN DE ELECTRICIDAD VALLE DE SANTA ANA, SL)

In [252]:
# https://distribucionpitarch.es/capacidad-nodal/epd
file_path = 'Excels/PITARCH_capacidad.xlsx'

# Read the Excel file
PITARCH_capacidad_df = pd.read_excel(file_path, sheet_name='Sheet1', header=[0]) 

columns = [
    'Provincia',
    'X',
    'Y',
    'Subestacion_REE',
    'Subestacion_PITARCH'
    ]

# Get unique rows based on 'Identificador de la Subestación'
PITARCH_df = PITARCH_capacidad_df[columns].drop_duplicates(subset='Subestacion_PITARCH')

# Display the resulting DataFrame
PITARCH_df

   Provincia          X           Y Subestacion_REE Subestacion_PITARCH
0    Cáceres  199917.30  4429030.62      Cáceres 22              EPST05
2    Cáceres  201049.89  4396689.77      Cáceres 22              EPST04
4    Cáceres  210578.28  4378398.69      Cáceres 22              EPST01
6    Cáceres  202249.51  4413110.45      Cáceres 22              EPST06
8    Cáceres  219711.08  4371036.79      Cáceres 22              EPST02
10   Cáceres  225531.02  4360567.77      Cáceres 22              EPST03
13   Cáceres  167646.44  4404137.21             NaN              EPST08

Convertir Coordenadas mostradas en el sistema de georreferenciación UTM ETRS89, huso 30 a coordenadas en WGS84 (EPSG:4326)

In [253]:
# Definimos el transformador
# EPSG:25830 -> ETRS89 / UTM zona 30N
# EPSG:4326  -> WGS84 (latitud, longitud)
transformer = Transformer.from_crs("EPSG:25830", "EPSG:4326", always_xy=True)

# Crear nuevas columnas con Latitud y Longitud en WGS84
PITARCH_df["Longitud"], PITARCH_df["Latitud"] = transformer.transform(PITARCH_df["X"].values, PITARCH_df["Y"].values)

Incluimos la comunidad autónoma asociada a cada provincia

In [254]:
# Aplicar la función a la columna 'provincia' y crear una nueva columna 'comunidad_autonoma'
PITARCH_df['Comunidad'] = PITARCH_df['Provincia'].apply(obtener_comunidad_autonoma)

PITARCH_df.to_excel('Excels/PITARCH.xlsx', index=False)

# BASSOLS

R1-015 (BASSOLS ENERGÍA, S.A)

In [255]:
# https://www.bassolsdistribucio.com/es/capacidades-de-acceso-a-la-red/
file_path = 'Excels/BASSOLS_capacidad.xlsx'

# Read the Excel file
BASSOLS_capacidad_df = pd.read_excel(file_path, sheet_name='Bassols', header=[0]) 

columns = [
    'Provincia',
    'X',
    'Y',
    'Subestacion_REE',
    'Subestacion_BASSOLS'
    ]

# Get unique rows based on 'Identificador de la Subestación'
BASSOLS_df = BASSOLS_capacidad_df[columns].drop_duplicates(subset='Subestacion_BASSOLS')

# Display the resulting DataFrame
BASSOLS_df

  Provincia         X          Y    Subestacion_REE Subestacion_BASSOLS
0    Girona  457956.0  4671023.5        BESCANO 400               SEOLO
1    Girona  478365.8  4669861.3  SANTA LLOGAIA 400               SESER
2    Girona  466028.3  4674236.8            VIC 400               SEPOL

Convertir Coordenadas mostradas en el sistema de georreferenciación UTM ETRS89, huso 30 a coordenadas en WGS84 (EPSG:4326)

In [256]:
# Definimos el transformador
# EPSG:25830 -> ETRS89 / UTM zona 30N
# EPSG:4326  -> WGS84 (latitud, longitud)
transformer = Transformer.from_crs("EPSG:25830", "EPSG:4326", always_xy=True)

# Crear nuevas columnas con Latitud y Longitud en WGS84
BASSOLS_df["Longitud"], BASSOLS_df["Latitud"] = transformer.transform(BASSOLS_df["X"].values, BASSOLS_df["Y"].values)

Incluimos la comunidad autónoma asociada a cada provincia

In [257]:
# Aplicar la función a la columna 'provincia' y crear una nueva columna 'comunidad_autonoma'
BASSOLS_df['Comunidad'] = BASSOLS_df['Provincia'].apply(obtener_comunidad_autonoma)

BASSOLS_df.to_excel('Excels/BASSOLS.xlsx', index=False)

# Maestrazgo

R1-017 (MAESTRAZGO DISTRIBUCION ELECTRICA SL)

In [258]:
# https://solredis.6eis.es/solredis-web/distributor/4
file_path = 'Excels/MAESTRAZGO_capacidad.xlsx'

# Read the Excel file
MAESTRAZGO_capacidad_df = pd.read_excel(file_path, sheet_name='Hoja1', header=[0]) 

columns = [
    'Provincia',
    'X',
    'Y',
    'Subestacion_REE',
    'Subestacion_MAESTRAZGO'
    ]

# Get unique rows based on 'Identificador de la Subestación'
MAESTRAZGO_df = MAESTRAZGO_capacidad_df[columns].drop_duplicates(subset='Subestacion_MAESTRAZGO')

# Display the resulting DataFrame
MAESTRAZGO_df

,Provincia,X,Y,Subestacion_REE,Subestacion_MAESTRAZGO
0,Castellón,785217.0317,4.495207e+06,NaN,90012
2,Castellón,745457.6681,4.500782e+06,NaN,38050
4,Teruel,732157.5643,4.524390e+06,NaN,90004
6,Teruel,726496.7554,4.519937e+06,NaN,13002
8,Castellón,748483.1235,4.506272e+06,NaN,38046

Convertir Coordenadas mostradas en el sistema de georreferenciación UTM ETRS89, huso 30 a coordenadas en WGS84 (EPSG:4326)

In [259]:
# Definimos el transformador
# EPSG:25830 -> ETRS89 / UTM zona 30N
# EPSG:4326  -> WGS84 (latitud, longitud)
transformer = Transformer.from_crs("EPSG:25830", "EPSG:4326", always_xy=True)

# Crear nuevas columnas con Latitud y Longitud en WGS84
MAESTRAZGO_df["Longitud"], MAESTRAZGO_df["Latitud"] = transformer.transform(MAESTRAZGO_df["X"].values, MAESTRAZGO_df["Y"].values)

Incluimos la comunidad autónoma asociada a cada provincia

In [260]:
# Aplicar la función a la columna 'provincia' y crear una nueva columna 'comunidad_autonoma'
MAESTRAZGO_df['Comunidad'] = MAESTRAZGO_df['Provincia'].apply(obtener_comunidad_autonoma)

MAESTRAZGO_df.to_excel('Excels/MAESTRAZGO.xlsx', index=False)

# GARVEY

R1-028 (MEDINA GARVEY ELECTRICIDAD, S.L.U.)

In [261]:
# https://medinagarveyelectricidad.oficinavirtual.sercide.com/embed/capacity-map
file_path = 'Excels/GARVEY_capacidad.xlsx'

# Read the Excel file
GARVEY_capacidad_df = pd.read_excel(file_path, sheet_name='Sheet1', header=[0]) 

columns = [
    'Provincia',
    'X',
    'Y',
    'Subestacion_REE',
    'Subestacion_GARVEY'
    ]

# Get unique rows based on 'Identificador de la Subestación'
GARVEY_df = GARVEY_capacidad_df[columns].drop_duplicates(subset='Subestacion_GARVEY')

# Display the resulting DataFrame
GARVEY_df

  Provincia          X           Y Subestacion_REE       Subestacion_GARVEY
0   Sevilla  206722.85  4132655.74       ROCIO 220          SE SANTA AMELIA
2   Sevilla  212785.10  4140585.56     CHUCENA 220             SE BENACAZON
4    Huelva  200258.01  4138155.03     CHUCENA 220  SUBESTACION CHUCENA-MGE

Convertir Coordenadas mostradas en el sistema de georreferenciación UTM ETRS89, huso 30 a coordenadas en WGS84 (EPSG:4326)

In [262]:
# Definimos el transformador
# EPSG:25830 -> ETRS89 / UTM zona 30N
# EPSG:4326  -> WGS84 (latitud, longitud)
transformer = Transformer.from_crs("EPSG:25830", "EPSG:4326", always_xy=True)

# Crear nuevas columnas con Latitud y Longitud en WGS84
GARVEY_df["Longitud"], GARVEY_df["Latitud"] = transformer.transform(GARVEY_df["X"].values, GARVEY_df["Y"].values)

Incluimos la comunidad autónoma asociada a cada provincia

In [263]:
# Aplicar la función a la columna 'provincia' y crear una nueva columna 'comunidad_autonoma'
GARVEY_df['Comunidad'] = GARVEY_df['Provincia'].apply(obtener_comunidad_autonoma)

GARVEY_df.to_excel('Excels/GARVEY.xlsx', index=False)

# CUERVA

R1-036 (DISTRIBUIDORA ELECTRICA BERMEJALES SL)

In [264]:
# https://distribucion.cuervaenergia.com/capacidades-nodales
file_path = 'Excels/CUERVA_capacidad.xlsx'

# Read the Excel file
CUERVA_capacidad_df = pd.read_excel(file_path, sheet_name='Hoja1', header=[0]) 

columns = [
    'Provincia',
    'X',
    'Y',
    'Subestacion_REE',
    'Subestacion_CUERVA'
    ]

# Get unique rows based on 'Identificador de la Subestación'
CUERVA_df = CUERVA_capacidad_df[columns].drop_duplicates(subset='Subestacion_CUERVA')

# Display the resulting DataFrame
CUERVA_df

  Provincia           X            Y Subestacion_REE   Subestacion_CUERVA
0   Granada  421627.108  4121813.753      Illora 220  036.SBT.JC308264128
1   Granada  433273.355  4104887.214             NaN   036.SBT.AP40000001

Convertir Coordenadas mostradas en el sistema de georreferenciación UTM ETRS89, huso 30 a coordenadas en WGS84 (EPSG:4326)

In [265]:
# Definimos el transformador
# EPSG:25830 -> ETRS89 / UTM zona 30N
# EPSG:4326  -> WGS84 (latitud, longitud)
transformer = Transformer.from_crs("EPSG:25830", "EPSG:4326", always_xy=True)

# Crear nuevas columnas con Latitud y Longitud en WGS84
CUERVA_df["Longitud"], CUERVA_df["Latitud"] = transformer.transform(CUERVA_df["X"].values, CUERVA_df["Y"].values)

Incluimos la comunidad autónoma asociada a cada provincia

In [266]:
# Aplicar la función a la columna 'provincia' y crear una nueva columna 'comunidad_autonoma'
CUERVA_df['Comunidad'] = CUERVA_df['Provincia'].apply(obtener_comunidad_autonoma)

CUERVA_df.to_excel('Excels/CUERVA.xlsx', index=False)

# ADURIZ

R1-090 (ADURIZ DISTRIBUCION SL)

In [267]:
# https://solredis.6eis.es/solredis-web/distributor/34
file_path = 'Excels/ADURIZ_capacidad.xlsx'

# Read the Excel file
ADURIZ_capacidad_df = pd.read_excel(file_path, sheet_name='Sheet1', header=[0]) 

columns = [
    'Provincia',
    'X',
    'Y',
    'Subestacion_REE',
    'Subestacion_ADURIZ'
    ]

# Get unique rows based on 'Identificador de la Subestación'
ADURIZ_df = ADURIZ_capacidad_df[columns].drop_duplicates(subset='Subestacion_ADURIZ')

# Display the resulting DataFrame
ADURIZ_df

  Provincia           X          Y  Subestacion_REE Subestacion_ADURIZ
0    Burgos  461119.969  4751447.5              NaN            STRM001
2    Burgos  459055.375  4752097.0              NaN            STRM002
4    Burgos  456922.875  4767664.0              NaN             STR003

Convertir Coordenadas mostradas en el sistema de georreferenciación UTM ETRS89, huso 30 a coordenadas en WGS84 (EPSG:4326)

In [268]:
# Definimos el transformador
# EPSG:25830 -> ETRS89 / UTM zona 30N
# EPSG:4326  -> WGS84 (latitud, longitud)
transformer = Transformer.from_crs("EPSG:25830", "EPSG:4326", always_xy=True)

# Crear nuevas columnas con Latitud y Longitud en WGS84
ADURIZ_df["Longitud"], ADURIZ_df["Latitud"] = transformer.transform(ADURIZ_df["X"].values, ADURIZ_df["Y"].values)

Incluimos la comunidad autónoma asociada a cada provincia

In [269]:
# Aplicar la función a la columna 'provincia' y crear una nueva columna 'comunidad_autonoma'
ADURIZ_df['Comunidad'] = ADURIZ_df['Provincia'].apply(obtener_comunidad_autonoma)

ADURIZ_df.to_excel('Excels/ADURIZ.xlsx', index=False)

# AGRI

R1-014 (AGRI-ENERGIA ELECTRICA, SA)

In [270]:
# https://solredis.6eis.es/solredis-web/distributor/1
file_path = 'Excels/AGRI_capacidad.xlsx'

# Read the Excel file
AGRI_capacidad_df = pd.read_excel(file_path, sheet_name='Hoja1', header=[0]) 

columns = [
    'Provincia',
    'X',
    'Y',
    'Subestacion_REE',
    'Subestacion_AGRI'
    ]

# Get unique rows based on 'Identificador de la Subestación'
AGRI_df = AGRI_capacidad_df[columns].drop_duplicates(subset='Subestacion_AGRI')

# Display the resulting DataFrame
AGRI_df

  Provincia       X        Y Subestacion_REE Subestacion_AGRI
0    Girona  485259  4654726        JUIA 220   SE PLAN ESTANY

Convertir Coordenadas mostradas en el sistema de georreferenciación UTM ETRS89, huso 31 a coordenadas en WGS84 (EPSG:4326)

In [271]:
# Definimos el transformador
# EPSG:25831 -> ETRS89 / UTM zona 31N
# EPSG:4326  -> WGS84 (latitud, longitud)
transformer = Transformer.from_crs("EPSG:25831", "EPSG:4326", always_xy=True)

# Crear nuevas columnas con Latitud y Longitud en WGS84
AGRI_df["Longitud"], AGRI_df["Latitud"] = transformer.transform(AGRI_df["X"].values, AGRI_df["Y"].values)

Incluimos la comunidad autónoma asociada a cada provincia

In [272]:
# Aplicar la función a la columna 'provincia' y crear una nueva columna 'comunidad_autonoma'
AGRI_df['Comunidad'] = AGRI_df['Provincia'].apply(obtener_comunidad_autonoma)

AGRI_df.to_excel('Excels/AGRI.xlsx', index=False)

# CALDENSE

R1-016 (ELECTRA CALDENSE S.A)

In [273]:
# https://solredis.6eis.es/solredis-web/distributor/3
file_path = 'Excels/CALDENSE_capacidad.xlsx'

# Read the Excel file
CALDENSE_capacidad_df = pd.read_excel(file_path, sheet_name='Hoja1', header=[0]) 

columns = [
    'Provincia',
    'X',
    'Y',
    'Subestacion_REE',
    'Subestacion_CALDENSE'
    ]

# Get unique rows based on 'Identificador de la Subestación'
CALDENSE_df = CALDENSE_capacidad_df[columns].drop_duplicates(subset='Subestacion_CALDENSE')

# Display the resulting DataFrame
CALDENSE_df

   Provincia          X            Y  Subestacion_REE Subestacion_CALDENSE
0  Barcelona  926227.25  4620129.116              NaN       SE CAN VINYALS

Convertir Coordenadas mostradas en el sistema de georreferenciación UTM ETRS89, huso 30 a coordenadas en WGS84 (EPSG:4326)

In [274]:
# Definimos el transformador
# EPSG:25830 -> ETRS89 / UTM zona 30N
# EPSG:4326  -> WGS84 (latitud, longitud)
transformer = Transformer.from_crs("EPSG:25830", "EPSG:4326", always_xy=True)

# Crear nuevas columnas con Latitud y Longitud en WGS84
CALDENSE_df["Longitud"], CALDENSE_df["Latitud"] = transformer.transform(CALDENSE_df["X"].values, CALDENSE_df["Y"].values)

Incluimos la comunidad autónoma asociada a cada provincia

In [275]:
# Aplicar la función a la columna 'provincia' y crear una nueva columna 'comunidad_autonoma'
CALDENSE_df['Comunidad'] = CALDENSE_df['Provincia'].apply(obtener_comunidad_autonoma)

CALDENSE_df.to_excel('Excels/CALDENSE.xlsx', index=False)

# GUADIELA

R1-023 (Hidroeléctrica del Guadiela I, S.A.)

In [276]:
# https://solredis.6eis.es/solredis-web/distributor/8
file_path = 'Excels/GUADIELA_capacidad.xlsx'

# Read the Excel file
GUADIELA_capacidad_df = pd.read_excel(file_path, sheet_name='Hoja1', header=[0]) 

columns = [
    'Provincia',
    'X',
    'Y',
    'Subestacion_REE',
    'Subestacion_GUADIELA'
    ]

# Get unique rows based on 'Identificador de la Subestación'
GUADIELA_df = GUADIELA_capacidad_df[columns].drop_duplicates(subset='Subestacion_GUADIELA')

# Display the resulting DataFrame
GUADIELA_df

ValueError: Worksheet named 'Hoja1' not found

Convertir Coordenadas mostradas en el sistema de georreferenciación UTM ETRS89, huso 30 a coordenadas en WGS84 (EPSG:4326)

In [ ]:
# Definimos el transformador
# EPSG:25830 -> ETRS89 / UTM zona 30N
# EPSG:4326  -> WGS84 (latitud, longitud)
transformer = Transformer.from_crs("EPSG:25830", "EPSG:4326", always_xy=True)

# Crear nuevas columnas con Latitud y Longitud en WGS84
GUADIELA_df["Longitud"], GUADIELA_df["Latitud"] = transformer.transform(GUADIELA_df["X"].values, GUADIELA_df["Y"].values)

Incluimos la comunidad autónoma asociada a cada provincia

In [ ]:
# Aplicar la función a la columna 'provincia' y crear una nueva columna 'comunidad_autonoma'
GUADIELA_df['Comunidad'] = GUADIELA_df['Provincia'].apply(obtener_comunidad_autonoma)

GUADIELA_df.to_excel('Excels/GUADIELA.xlsx', index=False)

# CREVILLENT

R1-033 (DISTRIBUCIÓN ELÉCTRICA CREVILLENT S.L.U.)

In [ ]:
# https://solredis.6eis.es/solredis-web/distributor/12
file_path = 'Excels/CREVILLENT_capacidad.xlsx'

# Read the Excel file
CREVILLENT_capacidad_df = pd.read_excel(file_path, sheet_name='Hoja1', header=[0]) 

columns = [
    'Provincia',
    'X',
    'Y',
    'Subestacion_REE',
    'Subestacion_PEUSA'
    ]

# Get unique rows based on 'Identificador de la Subestación'
CREVILLENT_df = CREVILLENT_capacidad_df[columns].drop_duplicates(subset='Subestacion_CREVILLENT')

# Display the resulting DataFrame
CREVILLENT_df

  Provincia         X           Y Subestacion_REE Subestacion_PEUSA
0    Lleida  862229.6  4695088.63          ADRALL         SE Adrall

Convertir Coordenadas mostradas en el sistema de georreferenciación UTM ETRS89, huso 30 a coordenadas en WGS84 (EPSG:4326)

In [ ]:
# Definimos el transformador
# EPSG:25830 -> ETRS89 / UTM zona 30N
# EPSG:4326  -> WGS84 (latitud, longitud)
transformer = Transformer.from_crs("EPSG:25830", "EPSG:4326", always_xy=True)

# Crear nuevas columnas con Latitud y Longitud en WGS84
CREVILLENT_df["Longitud"], CREVILLENT_df["Latitud"] = transformer.transform(CREVILLENT_df["X"].values, CREVILLENT_df["Y"].values)

Incluimos la comunidad autónoma asociada a cada provincia

In [ ]:
# Aplicar la función a la columna 'provincia' y crear una nueva columna 'comunidad_autonoma'
CREVILLENT_df['Comunidad'] = CREVILLENT_df['Provincia'].apply(obtener_comunidad_autonoma)

CREVILLENT_df.to_excel('Excels/CREVILLENT.xlsx', index=False)

# PEUSA

R1-020 (PEUSA DISTRIBUCIÓ, S.L.)

In [ ]:
# https://www.peusa.org/capacitats-dacces-i-connexio/?lang=es
file_path = 'Excels/PEUSA_capacidad.xlsx'

# Read the Excel file
PEUSA_capacidad_df = pd.read_excel(file_path, sheet_name='Hoja1', header=[0]) 

columns = [
    'Provincia',
    'X',
    'Y',
    'Subestacion_REE',
    'Subestacion_PEUSA'
    ]

# Get unique rows based on 'Identificador de la Subestación'
PEUSA_df = PEUSA_capacidad_df[columns].drop_duplicates(subset='Subestacion_PEUSA')

# Display the resulting DataFrame
PEUSA_df

  Provincia         X           Y Subestacion_REE Subestacion_PEUSA
0    Lleida  862229.6  4695088.63          ADRALL         SE Adrall

Convertir Coordenadas mostradas en el sistema de georreferenciación UTM ETRS89, huso 30 a coordenadas en WGS84 (EPSG:4326)

In [ ]:
# Definimos el transformador
# EPSG:25830 -> ETRS89 / UTM zona 30N
# EPSG:4326  -> WGS84 (latitud, longitud)
transformer = Transformer.from_crs("EPSG:25830", "EPSG:4326", always_xy=True)

# Crear nuevas columnas con Latitud y Longitud en WGS84
PEUSA_df["Longitud"], PEUSA_df["Latitud"] = transformer.transform(PEUSA_df["X"].values, PEUSA_df["Y"].values)

Incluimos la comunidad autónoma asociada a cada provincia

In [ ]:
# Aplicar la función a la columna 'provincia' y crear una nueva columna 'comunidad_autonoma'
PEUSA_df['Comunidad'] = PEUSA_df['Provincia'].apply(obtener_comunidad_autonoma)

PEUSA_df.to_excel('Excels/PEUSA.xlsx', index=False)

# ELÉCTRICA CONQUENSE DISTRIBUCIÓN S.A.

R1-009 (ELÉCTRICA CONQUENSE DISTRIBUCIÓN S.A.)

In [ ]:
# https://www.electricaconquense.es/conexion-a-la-red-electrica/
file_path = 'Excels/CONQUENSE_capacidad.xlsx'

# Read the Excel file
CONQUENSE_capacidad_df = pd.read_excel(file_path, sheet_name='Datos', header=[0]) 

columns = [
    'Provincia',
    'X',
    'Y',
    'Subestacion_REE',
    'Subestacion_CONQUENSE'
    ]

# Get unique rows based on 'Identificador de la Subestación'
CONQUENSE_df = CONQUENSE_capacidad_df[columns].drop_duplicates(subset='Subestacion_CONQUENSE')

# Display the resulting DataFrame
CONQUENSE_df

,Provincia,X,Y,Subestacion_REE,Subestacion_CONQUENSE
0,CUENCA,571408,4434681,BOLARQUE 132 / OLMEDILLA 132,ST EL TERMINILLO

Convertir Coordenadas mostradas en el sistema de georreferenciación UTM ETRS89, huso 30 a coordenadas en WGS84 (EPSG:4326)

In [ ]:
# Definimos el transformador
# EPSG:25830 -> ETRS89 / UTM zona 30N
# EPSG:4326  -> WGS84 (latitud, longitud)
transformer = Transformer.from_crs("EPSG:25830", "EPSG:4326", always_xy=True)

# Crear nuevas columnas con Latitud y Longitud en WGS84
CONQUENSE_df["Longitud"], CONQUENSE_df["Latitud"] = transformer.transform(CONQUENSE_df["X"].values, CONQUENSE_df["Y"].values)

Incluimos la comunidad autónoma asociada a cada provincia

In [ ]:
# Aplicar la función a la columna 'provincia' y crear una nueva columna 'comunidad_autonoma'
CONQUENSE_df['Comunidad'] = CONQUENSE_df['Provincia'].apply(obtener_comunidad_autonoma)

CONQUENSE_df.to_excel('Excels/CONQUENSE.xlsx', index=False)

# Consolidar todos en un solo fichero

In [ ]:
# Diccionario con los dataframes y sus nombres
dfs = {
    "iDE": iDE_df,
    "UFD": UFD_df,
    "EDRD": EDRD_df,
    "EREDES": EREDES_df,
    "VIESGO": VIESGO_df,
    "BEGASA": BEGASA_df,
    "ANELL": ANELL_df,
    "SEDC": SEDC_df,
    "EASA": EASA_df,
    "PITARCH": PITARCH_df,
    "BASSOLS": BASSOLS_df,
    "MAESTRAZGO": MAESTRAZGO_df,
    "GARVEY": GARVEY_df,
    "ADURIZ": ADURIZ_df,
    "AGRI": AGRI_df,
    "CALDENSE": CALDENSE_df,
    "CUERVA": CUERVA_df,
    "GUADIELA": GUADIELA_df,
    "CREVILLENT": CREVILLENT_df,
    "PEUSA": PEUSA_df,
    "CONQUENSE": CONQUENSE_df
}

# Lista donde guardaremos todos los dataframes transformados
normalized_dfs = []

for name, df in dfs.items():
    # Normalizamos las columnas según el patrón esperado
    df_tmp = pd.DataFrame({
        "Distribuidor": name,
        "Comunidad": df["Comunidad"],
        "Provincia": df["Provincia"],
        "Subestacion": df[f"Subestacion_{name}"],  # Ejemplo: Subestacion_iDE
        "lat": df["Latitud"],
        "lon": df["Longitud"],
        "Subestacion_REE": df["Subestacion_REE"]
    })
    normalized_dfs.append(df_tmp)

# Concatenamos todos en un solo DataFrame
subestaciones_distribucion_df = pd.concat(normalized_dfs, ignore_index=True)

subestaciones_distribucion_df

,Distribuidor,Comunidad,Provincia,Subestacion,lat,lon,Subestacion_REE
0,iDE,Castilla-La Mancha,ALBACETE,ST ALBACETE,39.019468,-1.893831,ROMICA 400
1,iDE,Castilla-La Mancha,ALBACETE,ST ALMANSA,38.852200,-1.087146,BENEJAMA 400
2,iDE,Castilla-La Mancha,ALBACETE,ST BARRAX,39.038773,-2.157478,ROMICA 400
3,iDE,Castilla-La Mancha,ALBACETE,ST CASAS IBAÑEZ,39.274190,-1.471269,ROMICA 400
4,iDE,Castilla-La Mancha,ALBACETE,ST EL BONILLO,38.949934,-2.527131,ROMICA 400
...,...,...,...,...,...,...,...
2750,AGRI,Cataluña,Girona,SE PLAN ESTANY,42.044443,2.821883,JUIA 220
2751,CUERVA,Andalucía,Granada,036.SBT.JC308264128,37.239560,-3.883601,Illora 220
2752,CUERVA,Andalucía,Granada,036.SBT.AP40000001,37.087901,-3.750798,NaN
2753,PEUSA,Cataluña,Lleida,SE Adrall,42.323752,1.395770,ADRALL
2754,CONQUENSE,Castilla-La Mancha,CUENCA,ST EL TERMINILLO,40.059356,-2.162726,BOLARQUE 132 / OLMEDILLA 132

In [ ]:
subestaciones_distribucion_df.to_excel('Excels/subestaciones_distribucion.xlsx', index=False)

In [ ]:
subestaciones_df = (
    subestaciones_distribucion_df[["Subestacion_REE", "Comunidad"]]
    .drop_duplicates()
    .sort_values(by="Subestacion_REE")
    .reset_index(drop=True)
)

subestaciones_df

    Subestacion_REE             Comunidad
0                 *              Cataluña
1                 *                Aragón
2      A determinar                Aragón
3      A determinar             Andalucía
4      ABADIANO 220            País Vasco
..              ...                   ...
548             NaN             Andalucía
549             NaN           Extremadura
550             NaN  Comunidad Valenciana
551             NaN                Aragón
552             NaN       Castilla y León

[553 rows x 2 columns]