In [1]:
!pip install pandas openpyxl pyproj

import pandas as pd

from pyproj import Transformer

Requirement already satisfied: pandas in /home/codespace/.local/lib/python3.12/site-packages (2.3.1)
Requirement already satisfied: openpyxl in /usr/local/python/3.12.1/lib/python3.12/site-packages (3.1.5)
Requirement already satisfied: pyproj in /usr/local/python/3.12.1/lib/python3.12/site-packages (3.7.2)
Requirement already satisfied: numpy>=1.26.0 in /home/codespace/.local/lib/python3.12/site-packages (from pandas) (2.3.1)
Requirement already satisfied: python-dateutil>=2.8.2 in /home/codespace/.local/lib/python3.12/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /home/codespace/.local/lib/python3.12/site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /home/codespace/.local/lib/python3.12/site-packages (from pandas) (2025.2)
Requirement already satisfied: et-xmlfile in /usr/local/python/3.12.1/lib/python3.12/site-packages (from openpyxl) (2.0.0)
Requirement already satisfied: certifi in /home/codespace/.local/lib/python3.12/site-packages (from pyproj) (2025.7.9)
Requirement already satisfied: six>=1.5 in /home/codespace/.local/lib/python3.12/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

[notice] A new release of pip is available: 25.1.1 -> 25.2
[notice] To update, run: python3 -m pip install --upgrade pip

# Distribuidores

## Listado de Distribuidoras de electricidad según REE

In [2]:
# https://www.esios.ree.es/es/descargas
file_path = 'Excels/124-Distribuidores.xlsx'  

distribuidores_ree_df = pd.read_excel(file_path)

distribuidores_ree_df

,Código,Empresa,Unidad,Fecha Alta,Estado
0,172,"ADURIZ DISTRIBUCIÓN, S.L.",R1-090,2009-01-07,VIGENTE
1,426,"AFRODÍSIO PASCUAL ALONSO, S.L.",R1-284,2009-01-04,VIGENTE
2,112,"AGRI ENERGÍA ELÉCTRICA, S.A.",R1-014,2009-01-03,VIGENTE
3,557,"AGRUPACIÓN DISTRIBUIDORA DE ESCUER, S.L.",R1-310,2009-01-07,VIGENTE
4,420,"ALARCÓN NAVARRO EMPRESA ELÉCTRICA, S.L.",R1-301,2009-01-07,VIGENTE
...,...,...,...,...,...
321,111,"UNIÓN DE DISTRIBUIDORES DE ELECTRICIDAD, S.A. ...",R1-042,2009-01-03,VIGENTE
322,169,"VALL DE SÓLLER ENERGÍA, S.L.U.",R1-056B,2019-01-03,VIGENTE
323,364,"VARGAS Y COMPAÑÍA ELECTRO HARINERA SAN RAMÓN, ...",R1-203,2009-01-07,VIGENTE
324,27,"VIESGO DISTRIBUCIÓN ELÉCTRICA, S.L.",R1-005,2009-01-07,VIGENTE
325,212,"VINALESA DISTRIBUCIÓN DE ENERGÍA, S.L.U.",R1-155,2009-01-07,VIGENTE

## Listado de Distribuidoras de electricidad según CNMC

In [3]:
# https://sede.cnmc.gob.es/listado/censo/1
file_path = 'Excels/distribuidoras.xlsx'  

distribuidores_cnmc_df = pd.read_excel(file_path)

distribuidores_cnmc_df

,NIF empresa,Numero,Nombre empresa,Teléfono gratuito incidencias,Portal de medidas
0,B22215487,R1-285,ENERGIAS DE BENASQUE S.L,900 102 303,https://portal.asemeservicios.com
1,B43986918,R1-360,ELECTRICA MUNICIPAL DE SANTA COLOMA DE QUERALT...,900 102 377,https://portal.asemeservicios.com
2,B63695167,R1-365,ELECTRA REDENERGIA SL,900 373 576,http://gestio.electraredenergia.com
3,B29749199,R1-196,ELECTRICA SERRANIA DE RONDA S.L,900 10 30 56,https://portal.asemeservicios.com
4,A22004675,R1-251,SERVICIOS URBANOS DE CERLER S.A.,900 102 387,https://portal.asemeservicios.com
...,...,...,...,...,...
328,B54863956,R1-063,"DISTRIBUCION ELECTRICA CATRALENSE, SLU",900 101 489,https://portal.asemeservicios.com
329,B98212053,R1-128,ELECTRICA DE CHERA DISTRIBUIDORA SL,900 373 319,http://consumos.grupcev.es
330,B91516351,R1-046,DISTRIBUIDORA ELECTRICA TENTUDIA SL,900 373 891,https://detentudia.oficinavirtual.sercide.com
331,B91516344,R1-199,DISTRIBUIDORA ELECTRICA MONESTERIO SL,900 373 874,https://demonesterio.oficinavirtual.sercide.com
332,B87689733,R1-133,HIDROELECTRICA EL CARMEN REDES SL,900 373 508,https://hidroelcarmen.oficinavirtual.sercide.com

Comparar ambas listas

In [4]:
unidad = distribuidores_ree_df['Unidad'].dropna().str.strip().unique()  
no_orden = distribuidores_cnmc_df['Numero'].dropna().str.strip().unique()  

# Convert to sets for efficient comparison
set_no_orden = set(no_orden)
set_unidad = set(unidad)

common_values = set_no_orden.intersection(set_unidad)  # Same values in both
missing_in_unidad = set_no_orden.difference(set_unidad)  # In Nº de orden but not in Unidad
missing_in_no_orden = set_unidad.difference(set_no_orden)  # In Unidad but not in Nº de orden

print("Número total de valores en el listado de REE:", len(set_unidad))
print("Número total de valores en el listado de la CNMC:", len(set_no_orden))
print("\nNúmero de valores comunes:", len(common_values))

Número total de valores en el listado de REE: 326
Número total de valores en el listado de la CNMC: 333

Número de valores comunes: 323

In [5]:
print("\nValores que están en el listado de la CNMC, pero no en el de REE:")

df_falta_en_REE = distribuidores_cnmc_df[distribuidores_cnmc_df['Numero'].isin(missing_in_unidad)]
df_falta_en_REE.style.hide(axis='index')

Valores que están en el listado de la CNMC, pero no en el de REE:

In [6]:
print("\nValores que están en el listado de REE, pero no en el de la CNMC:")

df_falta_en_CNMC = distribuidores_ree_df[distribuidores_ree_df['Unidad'].isin(missing_in_no_orden)]
df_falta_en_CNMC.style.hide(axis='index')

Valores que están en el listado de REE, pero no en el de la CNMC:

## Distribucion geográfica

In [7]:
def obtener_comunidad_autonoma(provincia):
    # Diccionario con provincias y sus comunidades autónomas
    comunidades = {
        'a coruña': 'Galicia',
        'alava': 'País Vasco',
        'albacete': 'Castilla-La Mancha',
        'alicante': 'Comunidad Valenciana',
        'almería': 'Andalucía',
        'asturias': 'Principado de Asturias',
        'avila': 'Castilla y León',
        'badajoz': 'Extremadura',
        'barcelona': 'Cataluña',
        'bizkaia': 'País Vasco',
        'burgos': 'Castilla y León',
        'caceres': 'Extremadura',
        'cadiz': 'Andalucía',
        'cantabria': 'Cantabria',
        'castellon': 'Comunidad Valenciana',
        'ciudad real': 'Castilla-La Mancha',
        'cordoba': 'Andalucía',
        'cuenca': 'Castilla-La Mancha',
        'girona': 'Cataluña',
        'granada': 'Andalucía',
        'guadalajara': 'Castilla-La Mancha',
        'gipuzkoa': 'País Vasco',
        'huelva': 'Andalucía',
        'huesca': 'Aragón',
        'islas baleares': 'Islas Baleares',
        'jaen': 'Andalucía',
        'la rioja': 'La Rioja',
        'las palmas': 'Islas Canarias',
        'leon': 'Castilla y León',
        'lleida': 'Cataluña',
        'lugo': 'Galicia',
        'madrid': 'Comunidad de Madrid',
        'malaga': 'Andalucía',
        'murcia': 'Región de Murcia',
        'navarra': 'Navarra',
        'ourense': 'Galicia',
        'palencia': 'Castilla y León',
        'pontevedra': 'Galicia',
        'salamanca': 'Castilla y León',
        'santa cruz de tenerife': 'Islas Canarias',
        'segovia': 'Castilla y León',
        'sevilla': 'Andalucía',
        'soria': 'Castilla y León',
        'tarragona': 'Cataluña',
        'teruel': 'Aragón',
        'toledo': 'Castilla-La Mancha',
        'valencia': 'Comunidad Valenciana',
        'valladolid': 'Castilla y León',
        'zamora': 'Castilla y León',
        'zaragoza': 'Aragón'
    }
    
    # Normalizar la entrada (minúsculas y sin tildes básicas)
    if isinstance(provincia, str):  # Asegurarse de que la entrada es una cadena
        provincia = provincia.lower().strip()
        provincia = provincia.replace('á', 'a').replace('é', 'e').replace('í', 'i').replace('ó', 'o').replace('ú', 'u')
        return comunidades.get(provincia, "Provincia no encontrada")
    return "Provincia no encontrada"

# I-DE Redes Eléctricas Inteligentes, S.A.U. (Grupo Iberdrola)

R1-001

In [8]:
# https://www.i-de.es/conexion-red-electrica/produccion-energia/mapa-capacidad-acceso
file_path = 'Excels/iDE_capacidad.xlsx'

# Read the Excel file
iDE_capacidad_df = pd.read_excel(file_path, sheet_name='Table 1', header=[0]) 

columns = [
    'Subestacion_iDE',
    'Municipio',
    'Provincia',
    'X',
    'Y',
    'Subestacion_REE'
]

# Get unique rows based on 'Identificador de la Subestación'
iDE_df = iDE_capacidad_df[columns].drop_duplicates(subset='Subestacion_iDE')

# Display the resulting DataFrame
iDE_df

,Subestacion_iDE,Municipio,Provincia,X,Y,Subestacion_REE
0,ST ALBACETE,ALBACETE,ALBACETE,595760.12,4319519.01,ROMICA 400
5,ST ALMANSA,ALMANSA,ALBACETE,665988.08,4302113.75,BENEJAMA 400
10,ST BARRAX,BARRAX,ALBACETE,572916.18,4321416.97,ROMICA 400
13,ST CASAS IBAÑEZ,CASAS IBAÑEZ,ALBACETE,631866.24,4348318.27,ROMICA 400
17,ST EL BONILLO,EL BONILLO,ALBACETE,540975.48,4311327.00,ROMICA 400
...,...,...,...,...,...,...
2983,STR TORO,TORO,ZAMORA,300258.21,4600161.15,ZAMORA 220
2987,STR VALDERREY,ZAMORA,ZAMORA,269756.98,4600268.56,ZAMORA 220
2991,STR VENTOSA,BENAVENTE,ZAMORA,277904.21,4652035.08,VILECHA 400
2993,STR VILLABRAZARO,VILLABRAZARO,ZAMORA,277490.35,4659689.16,VILECHA 400
2995,STR VILLALPANDO,VILLALPANDO,ZAMORA,297159.91,4638778.49,VILECHA 400

X and Y are the geographical coordinates of the subestation in the ETRS89 coordinate system expressed in meters. I want to convert them into WGS84 (EPSG:4326) coordinate system

In [9]:
# Definimos el transformador
# EPSG:25830 -> ETRS89 / UTM zona 30N
# EPSG:4326  -> WGS84 (latitud, longitud)
transformer = Transformer.from_crs("EPSG:25830", "EPSG:4326", always_xy=True)

# Crear nuevas columnas con Latitud y Longitud en WGS84
iDE_df["Longitud"], iDE_df["Latitud"] = transformer.transform(iDE_df["X"].values, iDE_df["Y"].values)

Incluimos la comunidad autónoma asociada a cada provincia

In [10]:
# Aplicar la función a la columna 'provincia' y crear una nueva columna 'comunidad_autonoma'
iDE_df['Comunidad'] = iDE_df['Provincia'].apply(obtener_comunidad_autonoma)

iDE_df.to_excel('Excels/iDE.xlsx', index=False)

# UFD DISTRIBUCIÓN ELECTRICIDAD, S.A. (Grupo Naturgy)

R1-002

In [11]:
# https://www.ufd.es/capacidad-de-acceso-de-generacion/
file_path = 'Excels/UFD_capacidad.xlsx'

# Read the Excel file
UFD_capacidad_df = pd.read_excel(file_path, sheet_name='Escenario Propuesta', header=[0]) 

columns = [
    'Subestacion_UFD',
    'Provincia',
    'X',
    'Y',
    'Subestacion_REE'
    ]

# Get unique rows based on 'Identificador de la Subestación'
UFD_df = UFD_capacidad_df[columns].drop_duplicates(subset='Subestacion_UFD')

UFD_df

      Subestacion_UFD    Provincia          X           Y   Subestacion_REE
0         C.T. NARCEA     ASTURIAS  224554.00  4798844.00        NARCEA 400
3       C.H.BURGUILLO        AVILA  370636.00  4476221.00  VILLAVICIOSA 400
6     C.H.PUENTENUEVO        AVILA  377683.00  4474588.00  VILLAVICIOSA 400
9                 ZAL    BARCELONA  929574.00  4586213.00           ZAL 220
12           ABENOJAR  CIUDAD REAL  382415.00  4305410.00       ALARCOS 220
...               ...          ...        ...         ...               ...
2007         YELES II       TOLEDO  432702.00  4441860.00     VALDEMORO 220
2013      LOS YEBENES       TOLEDO  426533.00  4380882.00    MADRIDEJOS 220
2019            YEPES       TOLEDO  447070.00  4416268.00     VALDEMORO 220
2025         COBREROS       ZAMORA  197049.54  4662902.57   SAN AGUSTIN 220
2028    MILLA DE TERA       ZAMORA  237921.00  4655964.00   COMPOSTILLA 400

[347 rows x 5 columns]

Coordenadas mostradas en el sistema de georreferenciación UTM ETRS89, huso 29 para las provincias de Lugo, Orense, La Coruña y Pontevedra. El resto de las provincias se muestran con el sistema de georreferenciación UTM ETRS89, huso 30. Convertir a coordenadas en WGS84 (EPSG:4326)

In [12]:
# Lista de provincias en huso 29
provincias_huso29 = ["Lugo", "Orense", "La Coruña", "Pontevedra"]

# Transformadores
transformer29 = Transformer.from_crs("EPSG:25829", "EPSG:4326", always_xy=True)
transformer30 = Transformer.from_crs("EPSG:25830", "EPSG:4326", always_xy=True)

# Función para convertir según provincia
def convertir_coord(row):
    x, y = row["X"], row["Y"]
    if row["Provincia"] in provincias_huso29:
        lon, lat = transformer29.transform(x, y)
    else:
        lon, lat = transformer30.transform(x, y)
    return pd.Series([lon, lat])

# Aplicar la conversión
UFD_df[["Longitud", "Latitud"]] = UFD_df.apply(convertir_coord, axis=1)

Incluimos la comunidad autónoma asociada a cada provincia

In [13]:
# Aplicar la función a la columna 'provincia' y crear una nueva columna 'comunidad_autonoma'
UFD_df['Comunidad'] = UFD_df['Provincia'].apply(obtener_comunidad_autonoma)

UFD_df.to_excel('Excels/UFD.xlsx', index=False)

# EDISTRIBUCIÓN REDES DIGITALES, S.L. (Grupo Enel)

R1-299, R1-299B

In [14]:
# https://www.edistribucion.com/es/red-electrica/Nodos_capacidad_acceso.html
file_path = 'Excels/EDRD_capacidad.xlsx'

# Read the Excel file
EDRD_capacidad_df = pd.read_excel(file_path, sheet_name='Table 1', header=[0]) 

columns = [
    'Comunidad',
    'Provincia',
    'Municipio',
    'Subestacion_EDRD',
    'Latitud',
    'Longitud',
    'Subestacion_REE'
    ]

# Get unique rows based on 'Identificador de la Subestación'
EDRD_df = EDRD_capacidad_df[columns].drop_duplicates(subset='Subestacion_EDRD')

EDRD_df

,Comunidad,Provincia,Municipio,Subestacion_EDRD,Latitud,Longitud,Subestacion_REE
0,01 - Andalucía,Almería,Roquetas de Mar,AGUADULC,36.813531,-2.598941,BERJA 220
2,01 - Andalucía,Almería,Albox,ALBOX,37.367600,-2.142758,LITORAL 400
4,01 - Andalucía,Almería,Alcolea,ALCOLEA,36.969459,-2.963403,BERJA 220
6,01 - Andalucía,Almería,Almería,ANDARAX,36.839727,-2.431844,LITORAL 400
9,01 - Andalucía,Almería,Almería,BELEN,36.850365,-2.474578,LITORAL 400
...,...,...,...,...,...,...,...
1829,11 - Extremadura,Badajoz,Castuera,ZUJAR,38.916248,-5.478426,VALDECABALLEROS 400
1830,12 - Galicia,"Coruña, A","Pontes de García Rodríguez, As",TESOURO,43.452366,-7.892504,PUENTES G.R. 400
1832,12 - Galicia,Ourense,Viana do Bolo,S.AGUSTIN,42.153497,-7.062870,S.AGUSTIN 220
1834,12 - Galicia,Ourense,Viana do Bolo,S.SEBAS,42.126101,-6.985063,S.AGUSTIN 220
1836,15 - Navarra,Navarra,Roncal/Erronkari,RONCAL,42.794116,-0.959489,SABIÑANIGO 220

In [15]:
# Eliminar el prefijo numérico y el guion
EDRD_df["Comunidad"] = EDRD_df["Comunidad"].str.replace(r'^\d+\s*-\s*', '', regex=True)

EDRD_df.to_excel('Excels/EDRD.xlsx', index=False)

# E-REDES Distribución Eléctrica (Grupo E-REDES)

R1-363 (ELECTRA DEL LLOBREGAT ENERGIA, S.L.), R1-008 (HIDROCANTÁBRICO DISTRIBUCIÓN ELÉCTRICA, S.A.)

In [16]:
# https://www.eredesdistribucion.es/mapa-interactivo-de-la-red
file_path = 'Excels/EREDES_capacidad.xlsx'

# Read the Excel file
EREDES_capacidad_df = pd.read_excel(file_path, sheet_name='Table 1', header=[0]) 

columns = [
    'Provincia',
    'X',
    'Y',
    'Subestacion_REE',
    'Subestacion_EREDES'
    ]

# Get unique rows based on 'Identificador de la Subestación'
EREDES_df = EREDES_capacidad_df[columns].drop_duplicates(subset='Subestacion_EREDES')

# Display the resulting DataFrame
EREDES_df

,Provincia,X,Y,Subestacion_REE,Subestacion_EREDES
0,Asturias,237341.32,4810817.19,SALAS 400,SE/CR ZORRINA
11,Asturias,312856.24,4803568.88,CARRIO 220,SE/CR VILLAMAYOR
20,Asturias,297336.57,4820931.19,CARRIO 220,SE/CR VENTA LAS RANAS
27,Asturias,274840.01,4801169.23,LADA 400,SE/CR VEGUIN 2
31,Asturias,274246.83,4832516.14,TABIELLA 220,SE/CR URB LA VALLINA 1
...,...,...,...,...,...
1214,Asturias,322490.10,4807772.73,LADA 400,SE ARRIONDAS
1227,Asturias,264322.28,4826404.03,TABIELLA 220,SE AMBULATORIO
1233,Asturias,273525.66,4814022.64,SIERO 220,SE ALIMERKA
1238,Valencia,715067.75,4369943.31,QUART DE POBLET 220,SE ALDAIA
1249,Barcelona,907279.22,4637263.42,*,SE PLANS DE LA SALA

Convertir Coordenadas mostradas en el sistema de georreferenciación UTM ETRS89, huso 30 a coordenadas en WGS84 (EPSG:4326)

In [17]:
# Definimos el transformador
# EPSG:25830 -> ETRS89 / UTM zona 30N
# EPSG:4326  -> WGS84 (latitud, longitud)
transformer = Transformer.from_crs("EPSG:25830", "EPSG:4326", always_xy=True)

# Crear nuevas columnas con Latitud y Longitud en WGS84
EREDES_df["Longitud"], EREDES_df["Latitud"] = transformer.transform(EREDES_df["X"].values, EREDES_df["Y"].values)

Incluimos la comunidad autónoma asociada a cada provincia

In [18]:
# Aplicar la función a la columna 'provincia' y crear una nueva columna 'comunidad_autonoma'
EREDES_df['Comunidad'] = EREDES_df['Provincia'].apply(obtener_comunidad_autonoma)

EREDES_df.to_excel('Excels/EREDES.xlsx', index=False)

# VIESGO distribución (Grupo EON)

R1-005 (VIESGO DISTRIBUCIÓN ELÉCTRICA, S.L.)

In [19]:
# https://www.viesgodistribucion.com/mapa-interactivo-de-la-red
file_path = 'Excels/VIESGO_capacidad.xlsx'

# Read the Excel file
VIESGO_capacidad_df = pd.read_excel(file_path, sheet_name='Table 1', header=[0]) 

columns = [
    'Provincia',
    'X',
    'Y',
    'Subestacion_REE',
    'Subestacion_VIESGO'
    ]

# Get unique rows based on 'Identificador de la Subestación'
VIESGO_df = VIESGO_capacidad_df[columns].drop_duplicates(subset='Subestacion_VIESGO')

# Display the resulting DataFrame
VIESGO_df

     Provincia       X        Y Subestacion_REE Subestacion_VIESGO
0     ASTURIAS  201593  4797451     EL PALO 400            EL PALO
3     ASTURIAS  187038  4794995       PESOZ 400              SANZO
15    ASTURIAS  215357  4825840       SALAS 400             ALMUÑA
31    ASTURIAS  198270  4820752       SALAS 400              ARBON
46    ASTURIAS  190402  4811140       SALAS 400             DOIRAS
...        ...     ...      ...             ...                ...
1127      LUGO  146551  4818040      LUDRIO 400          MONDOÑEDO
1134      LUGO  131875  4772615      LUDRIO 400         SAN CIBRAO
1137      LUGO  122821  4818556      P.G.R. 400              CARBA
1142      LUGO  121787  4806251      P.G.R. 400        SETE PONTES
1146      LUGO  170870  4828332       SALAS 400            RIBADEO

[96 rows x 5 columns]

Convertir Coordenadas mostradas en el sistema de georreferenciación UTM ETRS89, huso 30 a coordenadas en WGS84 (EPSG:4326)

In [20]:
# Definimos el transformador
# EPSG:25830 -> ETRS89 / UTM zona 30N
# EPSG:4326  -> WGS84 (latitud, longitud)
transformer = Transformer.from_crs("EPSG:25830", "EPSG:4326", always_xy=True)

# Crear nuevas columnas con Latitud y Longitud en WGS84
VIESGO_df["Longitud"], VIESGO_df["Latitud"] = transformer.transform(VIESGO_df["X"].values, VIESGO_df["Y"].values)

Incluimos la comunidad autónoma asociada a cada provincia

In [21]:
# Aplicar la función a la columna 'provincia' y crear una nueva columna 'comunidad_autonoma'
VIESGO_df['Comunidad'] = VIESGO_df['Provincia'].apply(obtener_comunidad_autonoma)

VIESGO_df.to_excel('Excels/VIESGO.xlsx', index=False)

# Consolidar todos en un solo fichero

In [22]:
# Diccionario con los dataframes y sus nombres
dfs = {
    "iDE": iDE_df,
    "UFD": UFD_df,
    "EDRD": EDRD_df,
    "EREDES": EREDES_df,
    "VIESGO": VIESGO_df
}

# Lista donde guardaremos todos los dataframes transformados
normalized_dfs = []

for name, df in dfs.items():
    # Normalizamos las columnas según el patrón esperado
    df_tmp = pd.DataFrame({
        "Distribuidor": name,
        "Comunidad": df["Comunidad"],
        "Provincia": df["Provincia"],
        "Subestacion": df[f"Subestacion_{name}"],  # Ejemplo: Subestacion_iDE
        "lat": df["Latitud"],
        "lon": df["Longitud"],
        "Subestacion_REE": df["Subestacion_REE"]
    })
    normalized_dfs.append(df_tmp)

# Concatenamos todos en un solo DataFrame
subestaciones_distribucion_df = pd.concat(normalized_dfs, ignore_index=True)

subestaciones_distribucion_df

,Distribuidor,Comunidad,Provincia,Subestacion,lat,lon,Subestacion_REE
0,iDE,Castilla-La Mancha,ALBACETE,ST ALBACETE,39.019468,-1.893831,ROMICA 400
1,iDE,Castilla-La Mancha,ALBACETE,ST ALMANSA,38.852200,-1.087146,BENEJAMA 400
2,iDE,Castilla-La Mancha,ALBACETE,ST BARRAX,39.038773,-2.157478,ROMICA 400
3,iDE,Castilla-La Mancha,ALBACETE,ST CASAS IBAÑEZ,39.274190,-1.471269,ROMICA 400
4,iDE,Castilla-La Mancha,ALBACETE,ST EL BONILLO,38.949934,-2.527131,ROMICA 400
...,...,...,...,...,...,...,...
2675,VIESGO,Galicia,LUGO,MONDOÑEDO,43.431832,-7.366825,LUDRIO 400
2676,VIESGO,Galicia,LUGO,SAN CIBRAO,43.017013,-7.517326,LUDRIO 400
2677,VIESGO,Galicia,LUGO,CARBA,43.424905,-7.659439,P.G.R. 400
2678,VIESGO,Galicia,LUGO,SETE PONTES,43.313952,-7.663684,P.G.R. 400
2679,VIESGO,Galicia,LUGO,RIBADEO,43.535342,-7.073355,SALAS 400

In [23]:
subestaciones_distribucion_df.to_excel('Excels/subestaciones_distribucion.xlsx', index=False)

In [25]:
subestaciones_df = (
    subestaciones_distribucion_df[["Subestacion_REE", "Comunidad"]]
    .drop_duplicates()
    .sort_values(by="Subestacion_REE")
    .reset_index(drop=True)
)

subestaciones_df

    Subestacion_REE        Comunidad
0                 *           Aragón
1                 *         Cataluña
2      A determinar        Andalucía
3      A determinar           Aragón
4      ABADIANO 220       País Vasco
..              ...              ...
526     VITORIA 220       País Vasco
527         ZAL 220         Cataluña
528      ZAMORA 220  Castilla y León
529     ZAMUDIO 220       País Vasco
530     ZARATAN 220  Castilla y León

[531 rows x 2 columns]