In [1]:
!pip install pandas openpyxl

import pandas as pd

Requirement already satisfied: pandas in /home/codespace/.local/lib/python3.12/site-packages (2.3.1)
Requirement already satisfied: openpyxl in /usr/local/python/3.12.1/lib/python3.12/site-packages (3.1.5)
Requirement already satisfied: numpy>=1.26.0 in /home/codespace/.local/lib/python3.12/site-packages (from pandas) (2.3.1)
Requirement already satisfied: python-dateutil>=2.8.2 in /home/codespace/.local/lib/python3.12/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /home/codespace/.local/lib/python3.12/site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /home/codespace/.local/lib/python3.12/site-packages (from pandas) (2025.2)
Requirement already satisfied: et-xmlfile in /usr/local/python/3.12.1/lib/python3.12/site-packages (from openpyxl) (2.0.0)
Requirement already satisfied: six>=1.5 in /home/codespace/.local/lib/python3.12/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

[notice] A new release of pip is available: 25.1.1 -> 25.2
[notice] To update, run: python3 -m pip install --upgrade pip

# Datos de REE

## Sujetos del mercado

In [2]:
# https://www.esios.ree.es/es/descargas
file_path = 'CSVs/sujetos-del-mercado.csv'

df_sujetos = pd.read_csv(file_path,sep=';')

df_sujetos

,Nombre,Codigo de sujeto,Codigo EIC,Tipo de SM
0,1,JOIN,18X0000000001RQ5,Consumidor directo mercado
1,18X000000000CICG,VIEPR,18X000000000CICG,Productor
2,18XATAL-12345-1E,ATAL,18XATAL-12345-1E,Productor
3,18XBURGE-1234--I,BURGE,18XBURGE-1234--I,Productor
4,18XMIRAS-12345-9,MIRAS,18XMIRAS-12345-9,Productor
...,...,...,...,...
743,ZEREP CARBONICAS Y AGUAS,ZERE,18XZERE-123456-V,Consumidor directo mercado
744,"ZERMATT POWER, SL",ZRMTT,18X000000000KBRC,Comercializador
745,ZETA ENERXIA GALEGA S.L.,ZETAE,18X000000000P6T3,Comercializador
746,"ZUG POWER, SL",ZUGPW,18X000000000MYC2,Comercializador
747,ZULUX ENERGIA,ZULU,18X000000000FBK9,Comercializador

## Unidades de programación

In [11]:
# https://www.esios.ree.es/es/descargas
file_path = 'CSVs/unidades-de-programacion.csv'

df_UP = pd.read_csv(file_path,sep=';',encoding='latin-1')

df_UP['Potencia maxima MW'] = df_UP['Potencia maxima MW'].str.replace('.', '', regex=False).str.replace(',', '.', regex=False).astype(float)

df_UP

,Codigo de UP,Descripcion corta,Descripcion larga,Potencia maxima MW,Codigo EIC,Tipo de produccion,Negocio,Zona de Regulacion,Sujeto del Mercado,Tipo de UP
0,A2GAME2,A2GAME2,A2GAME2,3.8,18W000000000R205,Energia residual,Venta,SZR,AME,Generacion
1,ABA1,ABA1,ABARAN,0.3,18WABA1-123456-K,Hidraulica UGH,Venta,SZR,BARER,Generacion
2,ABA2,ABA2,ABARAN 2,0.4,18WABA2-123456-A,Hidraulica UGH,Venta,SZR,BARER,Generacion
3,ABASC01,UPC ABAST,UP COMPRA ABASTE,1.0,18W000000000G8RE,Comercializadores mercado libre,Compra,SZR,ABAST,Comercializadores
4,ABO1,ABOÑO 1,C.T. ABOÑO 1,341.7,18WABO1-12345-0X,Hulla antracita,Venta,SZR,ABOGE,Generacion
...,...,...,...,...,...,...,...,...,...,...
3361,ZETAC01,ZETAC01,ZETAC01,0.1,18W000000000R93F,Comercializadores mercado libre,Compra,SZR,ZETAE,Comercializadores
3362,ZJARVE,ZJARVE,ZJARVE,6.0,18W000000000LAEE,Solar fotovoltaica,Venta,SZR,GNRA,Generacion
3363,ZRMTC01,ZERMATT,ZERMATT POWER,0.1,18W000000000L3YW,Comercializadores mercado libre,Compra,SZR,ZRMTT,Comercializadores
3364,ZUGPC01,ZUG POWER,ZUG POWER SL,0.1,18W000000000NER5,Comercializadores mercado libre,Compra,SZR,ZUGPW,Comercializadores
3365,ZULUC01,ZULU,ZULUX ENERGIA,0.2,18W000000000FCIO,Comercializadores mercado libre,Compra,SZR,ZULU,Comercializadores

## Unidades físicas

In [13]:
# https://www.esios.ree.es/es/descargas
file_path = 'CSVs/unidades-fisicas.csv'

df_UF = pd.read_csv(file_path,sep=';')

df_UF['Potencia maxima MW'] = df_UF['Potencia maxima MW'].str.replace('.', '', regex=False).str.replace(',', '.', regex=False).astype(float)

df_UF

,Codigo de UF,Codigo EIC,Descripcion,Potencia maxima MW,Tipo de produccion,Vinculacion con SM,Vinculacion con UP
0,3PINOS,18W0000000004ZX6,3PINOS - VELA,6.0,Solar fotovoltaica,GNRA,UPBLAN
1,3VILLAS,18W3VILLAS-123-5,PARQUE EÓLICO TRES VILLAS,49.5,Eolica terrestre,CEG,EUW3VIL
2,4CAM1,18W000000000RO29,CUATROCAMINOS1,6.2,Solar fotovoltaica,ADXRE,FAUDAX
3,4CAM2,18W000000000RO37,CUATROCAMINOS2,6.2,Solar fotovoltaica,ADXRE,FAUDAX
4,4CAM3,18W000000000RO45,CUATROCAMINOS4,3.7,Solar fotovoltaica,ADXRE,FAUDAX
...,...,...,...,...,...,...,...
5971,ZUM1,18WZUM1-12345-A0,ZUMARRESTA 1,1.5,Hidraulica UGH,IBEG,EBRA
5972,ZUM2,18WZUM2-12345-AR,ZUMARRESTA 2,2.0,Hidraulica UGH,IBEG,EBRA
5973,ZURBARA,18W000000000F6DF,FV ZURBARAN,34.3,Solar fotovoltaica,ECYR,FREGPEM
5974,ZUUVE,18W000000000LAGA,ZUUVE,2.0,Solar fotovoltaica,GNRA,ZJARVE
5975,ZWEUSK,18W000000000O3BT,UF ZWEUSK,12.0,Gas Natural Cogeneracion,NEXU,TESNELA

# Datos de la CNMC

## Listado de Consumidores directos del mercado de electricidad

In [14]:
# https://sede.cnmc.gob.es/listado/censo/8
file_path = 'Excels/consumidores.xlsx'  

consumidores_df = pd.read_excel(file_path)

consumidores_df

,Nº Orden,Nombre empresa,Domicilio titular,C.P.,Municipio,PROVINCIA,Estado
0,R3-0001,"JUAN JOSE MARTINEZ LOPEZ, S.A.","C/ LOPEZ DE HOCES, 7 -4º",14003,HORNACHUELOS,CORDOBA,NaN
1,R3-0002,EL YATE SOCIEDAD COOPERATIVA ANDALUZA,"CARRETERA NACIONAL IV, KM 393,200 A",14015,ALCOLEA,CORDOBA,NaN
2,R3-0003,SOCIEDAD AGRARIA DE TRANSFORMACIÓN DURAN Nº 9623,CARRETERA MAZARRÓN-PUERTO KM 10,30870,MAZARRON,MURCIA,NaN
3,R3-0006,COMPAÑÍA ESPAÑOLA DE LAMINACIÓN SL,POLIGONO INDUSTRIAL SAN VICENTE,8755,CASTELLBISBAL,BARCELONA,NaN
4,R3-0008,"JAMONES PESÓN, S.L.","C/ DOCTOR VELÁZQUEZ, 2 ; SEGORBE; CASTELLÓN",12400,ALBENTOSA,TERUEL,NaN
...,...,...,...,...,...,...,...
573,R3-0590,"REGASIFICADORA DEL NOROESTE, S.A.",PUNTA PROMONTORIO S/N,15620,MUGARDOS,A CORUÑA,NaN
574,R3-0591,"SELECCIO REGISA, S.L.","AVINGUDA MAS PINS, 106-112",17457,RIUDELLOTS DE LA SELVA,GIRONA,NaN
575,R3-0592,VIÑAOLIVA S. COOP.,"C/ AUTOMOCIÓN, 1 POL IND LAS PICADAS I",6200,ALMENDRALEJO,BADAJOZ,NaN
576,R3-0593,"LINAMAR LIGHT METALS ZARAGOZA, S.A.U.","CTRA CASTELLON CARTUJA BAJA, NUM. 6",50720,ZARAGOZA,ZARAGOZA,NaN
577,R3-0594,"ASTIGLASS, S.L.","P.I. LA CAMPIÑA. C/ DEHESA DE LAS YEGUAS, 1",41400,ÉCIJA,SEVILLA,NaN